// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/principal/principal.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.principal.model;

@kotlin.jvm.JvmName("-initializeinkPrincipal")
public inline fun inkPrincipal(block: ink.principal.model.InkPrincipalKt.Dsl.() -> kotlin.Unit): ink.principal.model.InkPrincipal =
  ink.principal.model.InkPrincipalKt.Dsl._create(ink.principal.model.InkPrincipal.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.principal.model.InkPrincipal`
 */
public object InkPrincipalKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.principal.model.InkPrincipal.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.principal.model.InkPrincipal.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.principal.model.InkPrincipal = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.id
      @JvmName("setId")
      set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RolesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string roles = 3;`
     * @return A list containing the roles.
     */
    public val roles: com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.rolesList
      )
    /**
     * `repeated string roles = 3;`
     * @param value The roles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRoles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.add(value: kotlin.String) {
      _builder.addRoles(value)
    }
    /**
     * `repeated string roles = 3;`
     * @param value The roles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRoles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string roles = 3;`
     * @param values The roles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRoles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllRoles(values)
    }
    /**
     * `repeated string roles = 3;`
     * @param values The roles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRoles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string roles = 3;`
     * @param index The index to set the value at.
     * @param value The roles to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRoles")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setRoles(index, value)
    }/**
     * `repeated string roles = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRoles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RolesProxy>.clear() {
      _builder.clearRoles()
    }
    /**
     * `bool is_llm = 4;`
     */
    public var isLlm: kotlin.Boolean
      @JvmName("getIsLlm")
      get() = _builder.isLlm
      @JvmName("setIsLlm")
      set(value) {
        _builder.isLlm = value
      }
    /**
     * `bool is_llm = 4;`
     */
    public fun clearIsLlm() {
      _builder.clearIsLlm()
    }

    /**
     * `string email = 5;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.email
      @JvmName("setEmail")
      set(value) {
        _builder.email = value
      }
    /**
     * `string email = 5;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.principal.model.InkPrincipal.copy(block: `ink.principal.model`.InkPrincipalKt.Dsl.() -> kotlin.Unit): ink.principal.model.InkPrincipal =
  `ink.principal.model`.InkPrincipalKt.Dsl._create(this.toBuilder()).apply { block() }._build()

