// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/asset.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializeassetCategory")
public inline fun assetCategory(block: AssetCategoryKt.Dsl.() -> kotlin.Unit): ink.java.model.AssetCategory =
  AssetCategoryKt.Dsl._create(ink.java.model.AssetCategory.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.AssetCategory`
 */
public object AssetCategoryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.AssetCategory.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.AssetCategory.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.AssetCategory = _builder.build()

    /**
     * ```
     * "🗡️"
     * ```
     *
     * `string emoji = 1;`
     */
    public var emoji: kotlin.String
      @JvmName("getEmoji")
      get() = _builder.emoji
      @JvmName("setEmoji")
      set(value) {
        _builder.emoji = value
      }
    /**
     * ```
     * "🗡️"
     * ```
     *
     * `string emoji = 1;`
     */
    public fun clearEmoji() {
      _builder.clearEmoji()
    }

    /**
     * ```
     * "sword"
     * ```
     *
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * ```
     * "sword"
     * ```
     *
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * weapon, armor, character, consumable, quest, currency
     * ```
     *
     * `string type = 3;`
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.type
      @JvmName("setType")
      set(value) {
        _builder.type = value
      }
    /**
     * ```
     * weapon, armor, character, consumable, quest, currency
     * ```
     *
     * `string type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * "sword_1h", "staff_2h", "cast"
     * ```
     *
     * `string anim_set = 4;`
     */
    public var animSet: kotlin.String
      @JvmName("getAnimSet")
      get() = _builder.animSet
      @JvmName("setAnimSet")
      set(value) {
        _builder.animSet = value
      }
    /**
     * ```
     * "sword_1h", "staff_2h", "cast"
     * ```
     *
     * `string anim_set = 4;`
     */
    public fun clearAnimSet() {
      _builder.clearAnimSet()
    }

    /**
     * ```
     * main_hand, off_hand, two_hand, none
     * ```
     *
     * `string grip_type = 5;`
     */
    public var gripType: kotlin.String
      @JvmName("getGripType")
      get() = _builder.gripType
      @JvmName("setGripType")
      set(value) {
        _builder.gripType = value
      }
    /**
     * ```
     * main_hand, off_hand, two_hand, none
     * ```
     *
     * `string grip_type = 5;`
     */
    public fun clearGripType() {
      _builder.clearGripType()
    }

    /**
     * ```
     * "weapon_sword", "char_wizard"
     * ```
     *
     * `string mesh_prefix = 6;`
     */
    public var meshPrefix: kotlin.String
      @JvmName("getMeshPrefix")
      get() = _builder.meshPrefix
      @JvmName("setMeshPrefix")
      set(value) {
        _builder.meshPrefix = value
      }
    /**
     * ```
     * "weapon_sword", "char_wizard"
     * ```
     *
     * `string mesh_prefix = 6;`
     */
    public fun clearMeshPrefix() {
      _builder.clearMeshPrefix()
    }

    /**
     * ```
     * "sfx_metal", "sfx_wood", "voice"
     * ```
     *
     * `string audio_category = 7;`
     */
    public var audioCategory: kotlin.String
      @JvmName("getAudioCategory")
      get() = _builder.audioCategory
      @JvmName("setAudioCategory")
      set(value) {
        _builder.audioCategory = value
      }
    /**
     * ```
     * "sfx_metal", "sfx_wood", "voice"
     * ```
     *
     * `string audio_category = 7;`
     */
    public fun clearAudioCategory() {
      _builder.clearAudioCategory()
    }

    /**
     * ```
     * Unicode metadata (from UnicodeDataLoader)
     * ```
     *
     * `string unicode_group = 8;`
     */
    public var unicodeGroup: kotlin.String
      @JvmName("getUnicodeGroup")
      get() = _builder.unicodeGroup
      @JvmName("setUnicodeGroup")
      set(value) {
        _builder.unicodeGroup = value
      }
    /**
     * ```
     * Unicode metadata (from UnicodeDataLoader)
     * ```
     *
     * `string unicode_group = 8;`
     */
    public fun clearUnicodeGroup() {
      _builder.clearUnicodeGroup()
    }

    /**
     * ```
     * "food-prepared", "sport"
     * ```
     *
     * `string unicode_subgroup = 9;`
     */
    public var unicodeSubgroup: kotlin.String
      @JvmName("getUnicodeSubgroup")
      get() = _builder.unicodeSubgroup
      @JvmName("setUnicodeSubgroup")
      set(value) {
        _builder.unicodeSubgroup = value
      }
    /**
     * ```
     * "food-prepared", "sport"
     * ```
     *
     * `string unicode_subgroup = 9;`
     */
    public fun clearUnicodeSubgroup() {
      _builder.clearUnicodeSubgroup()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CodePointsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     */
     public val codePoints: com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.codePointsList
      )
    /**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     * @param value The codePoints to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCodePoints")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.add(value: kotlin.Int) {
      _builder.addCodePoints(value)
    }/**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     * @param value The codePoints to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCodePoints")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     * @param values The codePoints to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCodePoints")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllCodePoints(values)
    }/**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     * @param values The codePoints to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCodePoints")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     * @param index The index to set the value at.
     * @param value The codePoints to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCodePoints")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setCodePoints(index, value)
    }/**
     * ```
     * UTF-32 codepoints [0x1F5E1]
     * ```
     *
     * `repeated int32 code_points = 10;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCodePoints")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CodePointsProxy>.clear() {
      _builder.clearCodePoints()
    }
    /**
     * ```
     * "7.0"
     * ```
     *
     * `string unicode_version = 11;`
     */
    public var unicodeVersion: kotlin.String
      @JvmName("getUnicodeVersion")
      get() = _builder.unicodeVersion
      @JvmName("setUnicodeVersion")
      set(value) {
        _builder.unicodeVersion = value
      }
    /**
     * ```
     * "7.0"
     * ```
     *
     * `string unicode_version = 11;`
     */
    public fun clearUnicodeVersion() {
      _builder.clearUnicodeVersion()
    }

    /**
     * ```
     * "So" (Symbol, other)
     * ```
     *
     * `string general_category = 12;`
     */
    public var generalCategory: kotlin.String
      @JvmName("getGeneralCategory")
      get() = _builder.generalCategory
      @JvmName("setGeneralCategory")
      set(value) {
        _builder.generalCategory = value
      }
    /**
     * ```
     * "So" (Symbol, other)
     * ```
     *
     * `string general_category = 12;`
     */
    public fun clearGeneralCategory() {
      _builder.clearGeneralCategory()
    }

    /**
     * ```
     * true if maps to 3D asset pipeline
     * ```
     *
     * `bool is_game_asset = 13;`
     */
    public var isGameAsset: kotlin.Boolean
      @JvmName("getIsGameAsset")
      get() = _builder.isGameAsset
      @JvmName("setIsGameAsset")
      set(value) {
        _builder.isGameAsset = value
      }
    /**
     * ```
     * true if maps to 3D asset pipeline
     * ```
     *
     * `bool is_game_asset = 13;`
     */
    public fun clearIsGameAsset() {
      _builder.clearIsGameAsset()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.AssetCategory.copy(block: AssetCategoryKt.Dsl.() -> kotlin.Unit): ink.java.model.AssetCategory =
  AssetCategoryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

