// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/ical.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializeattendee")
public inline fun attendee(block: AttendeeKt.Dsl.() -> kotlin.Unit): ink.java.model.Attendee =
  AttendeeKt.Dsl._create(ink.java.model.Attendee.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.Attendee`
 */
public object AttendeeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.Attendee.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.Attendee.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.Attendee = _builder.build()

    /**
     * ```
     * mailto:user@example.com
     * ```
     *
     * `string cal_address = 1;`
     */
    public var calAddress: kotlin.String
      @JvmName("getCalAddress")
      get() = _builder.calAddress
      @JvmName("setCalAddress")
      set(value) {
        _builder.calAddress = value
      }
    /**
     * ```
     * mailto:user@example.com
     * ```
     *
     * `string cal_address = 1;`
     */
    public fun clearCalAddress() {
      _builder.clearCalAddress()
    }

    /**
     * ```
     * CN parameter
     * ```
     *
     * `string common_name = 2;`
     */
    public var commonName: kotlin.String
      @JvmName("getCommonName")
      get() = _builder.commonName
      @JvmName("setCommonName")
      set(value) {
        _builder.commonName = value
      }
    /**
     * ```
     * CN parameter
     * ```
     *
     * `string common_name = 2;`
     */
    public fun clearCommonName() {
      _builder.clearCommonName()
    }

    /**
     * `.ink.model.ParticipantRole role = 3;`
     */
    public var role: ink.java.model.ParticipantRole
      @JvmName("getRole")
      get() = _builder.role
      @JvmName("setRole")
      set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @JvmName("getRoleValue")
      get() = _builder.roleValue
      @JvmName("setRoleValue")
      set(value) {
        _builder.roleValue = value
      }
    /**
     * `.ink.model.ParticipantRole role = 3;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `.ink.model.ParticipationStatus partstat = 4;`
     */
    public var partstat: ink.java.model.ParticipationStatus
      @JvmName("getPartstat")
      get() = _builder.partstat
      @JvmName("setPartstat")
      set(value) {
        _builder.partstat = value
      }
    public var partstatValue: kotlin.Int
      @JvmName("getPartstatValue")
      get() = _builder.partstatValue
      @JvmName("setPartstatValue")
      set(value) {
        _builder.partstatValue = value
      }
    /**
     * `.ink.model.ParticipationStatus partstat = 4;`
     */
    public fun clearPartstat() {
      _builder.clearPartstat()
    }

    /**
     * `bool rsvp = 5;`
     */
    public var rsvp: kotlin.Boolean
      @JvmName("getRsvp")
      get() = _builder.rsvp
      @JvmName("setRsvp")
      set(value) {
        _builder.rsvp = value
      }
    /**
     * `bool rsvp = 5;`
     */
    public fun clearRsvp() {
      _builder.clearRsvp()
    }

    /**
     * ```
     * DELEGATED-FROM
     * ```
     *
     * `string delegated_from = 6;`
     */
    public var delegatedFrom: kotlin.String
      @JvmName("getDelegatedFrom")
      get() = _builder.delegatedFrom
      @JvmName("setDelegatedFrom")
      set(value) {
        _builder.delegatedFrom = value
      }
    /**
     * ```
     * DELEGATED-FROM
     * ```
     *
     * `string delegated_from = 6;`
     */
    public fun clearDelegatedFrom() {
      _builder.clearDelegatedFrom()
    }

    /**
     * ```
     * DELEGATED-TO
     * ```
     *
     * `string delegated_to = 7;`
     */
    public var delegatedTo: kotlin.String
      @JvmName("getDelegatedTo")
      get() = _builder.delegatedTo
      @JvmName("setDelegatedTo")
      set(value) {
        _builder.delegatedTo = value
      }
    /**
     * ```
     * DELEGATED-TO
     * ```
     *
     * `string delegated_to = 7;`
     */
    public fun clearDelegatedTo() {
      _builder.clearDelegatedTo()
    }

    /**
     * ```
     * SENT-BY
     * ```
     *
     * `string sent_by = 8;`
     */
    public var sentBy: kotlin.String
      @JvmName("getSentBy")
      get() = _builder.sentBy
      @JvmName("setSentBy")
      set(value) {
        _builder.sentBy = value
      }
    /**
     * ```
     * SENT-BY
     * ```
     *
     * `string sent_by = 8;`
     */
    public fun clearSentBy() {
      _builder.clearSentBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.Attendee.copy(block: AttendeeKt.Dsl.() -> kotlin.Unit): ink.java.model.Attendee =
  AttendeeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

