// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/collab.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializeeditorContext")
public inline fun editorContext(block: EditorContextKt.Dsl.() -> kotlin.Unit): ink.java.model.EditorContext =
  EditorContextKt.Dsl._create(ink.java.model.EditorContext.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.EditorContext`
 */
public object EditorContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.EditorContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.EditorContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.EditorContext = _builder.build()

    /**
     * ```
     * "edit" or "play"
     * ```
     *
     * `string mode = 1;`
     */
    public var mode: kotlin.String
      @JvmName("getMode")
      get() = _builder.mode
      @JvmName("setMode")
      set(value) {
        _builder.mode = value
      }
    /**
     * ```
     * "edit" or "play"
     * ```
     *
     * `string mode = 1;`
     */
    public fun clearMode() {
      _builder.clearMode()
    }

    /**
     * `string session_id = 2;`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 2;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string doc_id = 3;`
     */
    public var docId: kotlin.String
      @JvmName("getDocId")
      get() = _builder.docId
      @JvmName("setDocId")
      set(value) {
        _builder.docId = value
      }
    /**
     * `string doc_id = 3;`
     */
    public fun clearDocId() {
      _builder.clearDocId()
    }

    /**
     * `bool is_compiling = 4;`
     */
    public var isCompiling: kotlin.Boolean
      @JvmName("getIsCompiling")
      get() = _builder.isCompiling
      @JvmName("setIsCompiling")
      set(value) {
        _builder.isCompiling = value
      }
    /**
     * `bool is_compiling = 4;`
     */
    public fun clearIsCompiling() {
      _builder.clearIsCompiling()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ErrorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string errors = 5;`
     * @return A list containing the errors.
     */
    public val errors: com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.errorsList
      )
    /**
     * `repeated string errors = 5;`
     * @param value The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addErrors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.add(value: kotlin.String) {
      _builder.addErrors(value)
    }
    /**
     * `repeated string errors = 5;`
     * @param value The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string errors = 5;`
     * @param values The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllErrors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllErrors(values)
    }
    /**
     * `repeated string errors = 5;`
     * @param values The errors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string errors = 5;`
     * @param index The index to set the value at.
     * @param value The errors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setErrors")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setErrors(index, value)
    }/**
     * `repeated string errors = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearErrors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ErrorsProxy>.clear() {
      _builder.clearErrors()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.EditorContext.copy(block: EditorContextKt.Dsl.() -> kotlin.Unit): ink.java.model.EditorContext =
  EditorContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

