// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/vcard.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializejCard")
public inline fun jCard(block: JCardKt.Dsl.() -> kotlin.Unit): ink.java.model.JCard =
  JCardKt.Dsl._create(ink.java.model.JCard.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.JCard`
 */
public object JCardKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.JCard.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.JCard.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.JCard = _builder.build()

    /**
     * ```
     * Raw jCard JSON string
     * ```
     *
     * `string json = 1;`
     */
    public var json: kotlin.String
      @JvmName("getJson")
      get() = _builder.json
      @JvmName("setJson")
      set(value) {
        _builder.json = value
      }
    /**
     * ```
     * Raw jCard JSON string
     * ```
     *
     * `string json = 1;`
     */
    public fun clearJson() {
      _builder.clearJson()
    }

    /**
     * ```
     * Parsed vCard fields
     * ```
     *
     * `.ink.model.InkVCard parsed = 2;`
     */
    public var parsed: ink.java.model.InkVCard
      @JvmName("getParsed")
      get() = _builder.parsed
      @JvmName("setParsed")
      set(value) {
        _builder.parsed = value
      }
    /**
     * ```
     * Parsed vCard fields
     * ```
     *
     * `.ink.model.InkVCard parsed = 2;`
     */
    public fun clearParsed() {
      _builder.clearParsed()
    }
    /**
     * ```
     * Parsed vCard fields
     * ```
     *
     * `.ink.model.InkVCard parsed = 2;`
     * @return Whether the parsed field is set.
     */
    public fun hasParsed(): kotlin.Boolean {
      return _builder.hasParsed()
    }
    public val JCardKt.Dsl.parsedOrNull: ink.java.model.InkVCard?
      get() = _builder.parsedOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.JCard.copy(block: JCardKt.Dsl.() -> kotlin.Unit): ink.java.model.JCard =
  JCardKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ink.java.model.JCardOrBuilder.parsedOrNull: ink.java.model.InkVCard?
  get() = if (hasParsed()) getParsed() else null

