// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/mcp.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializejsonRpcError")
public inline fun jsonRpcError(block: JsonRpcErrorKt.Dsl.() -> kotlin.Unit): ink.java.model.JsonRpcError =
  JsonRpcErrorKt.Dsl._create(ink.java.model.JsonRpcError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.JsonRpcError`
 */
public object JsonRpcErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.JsonRpcError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.JsonRpcError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.JsonRpcError = _builder.build()

    /**
     * `int32 code = 1;`
     */
    public var code: kotlin.Int
      @JvmName("getCode")
      get() = _builder.code
      @JvmName("setCode")
      set(value) {
        _builder.code = value
      }
    /**
     * `int32 code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `string data_json = 3;`
     */
    public var dataJson: kotlin.String
      @JvmName("getDataJson")
      get() = _builder.dataJson
      @JvmName("setDataJson")
      set(value) {
        _builder.dataJson = value
      }
    /**
     * `string data_json = 3;`
     */
    public fun clearDataJson() {
      _builder.clearDataJson()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.JsonRpcError.copy(block: JsonRpcErrorKt.Dsl.() -> kotlin.Unit): ink.java.model.JsonRpcError =
  JsonRpcErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

