// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/mcp.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.kt.model;

@kotlin.jvm.JvmName("-initializemcpCapabilities")
public inline fun mcpCapabilities(block: McpCapabilitiesKt.Dsl.() -> kotlin.Unit): ink.java.model.McpCapabilities =
  McpCapabilitiesKt.Dsl._create(ink.java.model.McpCapabilities.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.model.McpCapabilities`
 */
public object McpCapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.java.model.McpCapabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.java.model.McpCapabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.java.model.McpCapabilities = _builder.build()

    /**
     * `.ink.model.McpToolCapability tools = 1;`
     */
    public var tools: ink.java.model.McpToolCapability
      @JvmName("getTools")
      get() = _builder.tools
      @JvmName("setTools")
      set(value) {
        _builder.tools = value
      }
    /**
     * `.ink.model.McpToolCapability tools = 1;`
     */
    public fun clearTools() {
      _builder.clearTools()
    }
    /**
     * `.ink.model.McpToolCapability tools = 1;`
     * @return Whether the tools field is set.
     */
    public fun hasTools(): kotlin.Boolean {
      return _builder.hasTools()
    }
    public val McpCapabilitiesKt.Dsl.toolsOrNull: ink.java.model.McpToolCapability?
      get() = _builder.toolsOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.java.model.McpCapabilities.copy(block: McpCapabilitiesKt.Dsl.() -> kotlin.Unit): ink.java.model.McpCapabilities =
  McpCapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ink.java.model.McpCapabilitiesOrBuilder.toolsOrNull: ink.java.model.McpToolCapability?
  get() = if (hasTools()) getTools() else null

