// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/calendar/calendar.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.calendar.model;

@kotlin.jvm.JvmName("-initializeinkEvent")
public inline fun inkEvent(block: ink.calendar.model.InkEventKt.Dsl.() -> kotlin.Unit): ink.calendar.model.InkEvent =
  ink.calendar.model.InkEventKt.Dsl._create(ink.calendar.model.InkEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.calendar.model.InkEvent`
 */
public object InkEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.calendar.model.InkEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.calendar.model.InkEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.calendar.model.InkEvent = _builder.build()

    /**
     * `string uid = 1;`
     */
    public var uid: kotlin.String
      @JvmName("getUid")
      get() = _builder.uid
      @JvmName("setUid")
      set(value) {
        _builder.uid = value
      }
    /**
     * `string uid = 1;`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * `string summary = 2;`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * `string summary = 2;`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }

    /**
     * `string description = 3;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 3;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string dt_start = 4;`
     */
    public var dtStart: kotlin.String
      @JvmName("getDtStart")
      get() = _builder.dtStart
      @JvmName("setDtStart")
      set(value) {
        _builder.dtStart = value
      }
    /**
     * `string dt_start = 4;`
     */
    public fun clearDtStart() {
      _builder.clearDtStart()
    }

    /**
     * `string dt_end = 5;`
     */
    public var dtEnd: kotlin.String
      @JvmName("getDtEnd")
      get() = _builder.dtEnd
      @JvmName("setDtEnd")
      set(value) {
        _builder.dtEnd = value
      }
    /**
     * `string dt_end = 5;`
     */
    public fun clearDtEnd() {
      _builder.clearDtEnd()
    }

    /**
     * `string category = 6;`
     */
    public var category: kotlin.String
      @JvmName("getCategory")
      get() = _builder.category
      @JvmName("setCategory")
      set(value) {
        _builder.category = value
      }
    /**
     * `string category = 6;`
     */
    public fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * `string location = 7;`
     */
    public var location: kotlin.String
      @JvmName("getLocation")
      get() = _builder.location
      @JvmName("setLocation")
      set(value) {
        _builder.location = value
      }
    /**
     * `string location = 7;`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }

    /**
     * `string status = 8;`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    /**
     * `string status = 8;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.calendar.model.InkEvent.copy(block: `ink.calendar.model`.InkEventKt.Dsl.() -> kotlin.Unit): ink.calendar.model.InkEvent =
  `ink.calendar.model`.InkEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

