// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/vcard/vcard.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.vcard.model;

@kotlin.jvm.JvmName("-initializevCardEmail")
public inline fun vCardEmail(block: ink.vcard.model.VCardEmailKt.Dsl.() -> kotlin.Unit): ink.vcard.model.VCardEmail =
  ink.vcard.model.VCardEmailKt.Dsl._create(ink.vcard.model.VCardEmail.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.vcard.model.VCardEmail`
 */
public object VCardEmailKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.vcard.model.VCardEmail.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.vcard.model.VCardEmail.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.vcard.model.VCardEmail = _builder.build()

    /**
     * `.ink.vcard.model.EmailType type = 1;`
     */
    public var type: ink.vcard.model.EmailType
      @JvmName("getType")
      get() = _builder.type
      @JvmName("setType")
      set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.typeValue
      @JvmName("setTypeValue")
      set(value) {
        _builder.typeValue = value
      }
    /**
     * `.ink.vcard.model.EmailType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string value = 2;`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * `string value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * `bool is_preferred = 3;`
     */
    public var isPreferred: kotlin.Boolean
      @JvmName("getIsPreferred")
      get() = _builder.isPreferred
      @JvmName("setIsPreferred")
      set(value) {
        _builder.isPreferred = value
      }
    /**
     * `bool is_preferred = 3;`
     */
    public fun clearIsPreferred() {
      _builder.clearIsPreferred()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.vcard.model.VCardEmail.copy(block: `ink.vcard.model`.VCardEmailKt.Dsl.() -> kotlin.Unit): ink.vcard.model.VCardEmail =
  `ink.vcard.model`.VCardEmailKt.Dsl._create(this.toBuilder()).apply { block() }._build()

