// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/sillytavern/sillytavern.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.sillytavern.model;

@kotlin.jvm.JvmName("-initializestCharacterCard")
public inline fun stCharacterCard(block: ink.sillytavern.model.StCharacterCardKt.Dsl.() -> kotlin.Unit): ink.sillytavern.model.StCharacterCard =
  ink.sillytavern.model.StCharacterCardKt.Dsl._create(ink.sillytavern.model.StCharacterCard.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.sillytavern.model.StCharacterCard`
 */
public object StCharacterCardKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.sillytavern.model.StCharacterCard.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.sillytavern.model.StCharacterCard.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.sillytavern.model.StCharacterCard = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 2;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 2;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string personality = 3;`
     */
    public var personality: kotlin.String
      @JvmName("getPersonality")
      get() = _builder.personality
      @JvmName("setPersonality")
      set(value) {
        _builder.personality = value
      }
    /**
     * `string personality = 3;`
     */
    public fun clearPersonality() {
      _builder.clearPersonality()
    }

    /**
     * `string scenario = 4;`
     */
    public var scenario: kotlin.String
      @JvmName("getScenario")
      get() = _builder.scenario
      @JvmName("setScenario")
      set(value) {
        _builder.scenario = value
      }
    /**
     * `string scenario = 4;`
     */
    public fun clearScenario() {
      _builder.clearScenario()
    }

    /**
     * `string first_message = 5;`
     */
    public var firstMessage: kotlin.String
      @JvmName("getFirstMessage")
      get() = _builder.firstMessage
      @JvmName("setFirstMessage")
      set(value) {
        _builder.firstMessage = value
      }
    /**
     * `string first_message = 5;`
     */
    public fun clearFirstMessage() {
      _builder.clearFirstMessage()
    }

    /**
     * `string mes_example = 6;`
     */
    public var mesExample: kotlin.String
      @JvmName("getMesExample")
      get() = _builder.mesExample
      @JvmName("setMesExample")
      set(value) {
        _builder.mesExample = value
      }
    /**
     * `string mes_example = 6;`
     */
    public fun clearMesExample() {
      _builder.clearMesExample()
    }

    /**
     * `string system_prompt = 7;`
     */
    public var systemPrompt: kotlin.String
      @JvmName("getSystemPrompt")
      get() = _builder.systemPrompt
      @JvmName("setSystemPrompt")
      set(value) {
        _builder.systemPrompt = value
      }
    /**
     * `string system_prompt = 7;`
     */
    public fun clearSystemPrompt() {
      _builder.clearSystemPrompt()
    }

    /**
     * `string creator_notes = 8;`
     */
    public var creatorNotes: kotlin.String
      @JvmName("getCreatorNotes")
      get() = _builder.creatorNotes
      @JvmName("setCreatorNotes")
      set(value) {
        _builder.creatorNotes = value
      }
    /**
     * `string creator_notes = 8;`
     */
    public fun clearCreatorNotes() {
      _builder.clearCreatorNotes()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tags = 9;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.tagsList
      )
    /**
     * `repeated string tags = 9;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * `repeated string tags = 9;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tags = 9;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * `repeated string tags = 9;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tags = 9;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * `repeated string tags = 9;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.sillytavern.model.StCharacterCard.copy(block: `ink.sillytavern.model`.StCharacterCardKt.Dsl.() -> kotlin.Unit): ink.sillytavern.model.StCharacterCard =
  `ink.sillytavern.model`.StCharacterCardKt.Dsl._create(this.toBuilder()).apply { block() }._build()

