// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/document/document.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.document.model;

@kotlin.jvm.JvmName("-initializeinkFile")
public inline fun inkFile(block: ink.document.model.InkFileKt.Dsl.() -> kotlin.Unit): ink.document.model.InkFile =
  ink.document.model.InkFileKt.Dsl._create(ink.document.model.InkFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.document.model.InkFile`
 */
public object InkFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.document.model.InkFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.document.model.InkFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.document.model.InkFile = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string ink_source = 2;`
     */
    public var inkSource: kotlin.String
      @JvmName("getInkSource")
      get() = _builder.inkSource
      @JvmName("setInkSource")
      set(value) {
        _builder.inkSource = value
      }
    /**
     * `string ink_source = 2;`
     */
    public fun clearInkSource() {
      _builder.clearInkSource()
    }

    /**
     * `int32 header_level = 3;`
     */
    public var headerLevel: kotlin.Int
      @JvmName("getHeaderLevel")
      get() = _builder.headerLevel
      @JvmName("setHeaderLevel")
      set(value) {
        _builder.headerLevel = value
      }
    /**
     * `int32 header_level = 3;`
     */
    public fun clearHeaderLevel() {
      _builder.clearHeaderLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.document.model.InkFile.copy(block: `ink.document.model`.InkFileKt.Dsl.() -> kotlin.Unit): ink.document.model.InkFile =
  `ink.document.model`.InkFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

