// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/story/story.proto
// Protobuf Java Version: 4.28.3

package ink.story.model;

public interface StorySessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.story.model.StorySession)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string source = 2;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 2;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string state_json = 3;</code>
   * @return The stateJson.
   */
  java.lang.String getStateJson();
  /**
   * <code>string state_json = 3;</code>
   * @return The bytes for stateJson.
   */
  com.google.protobuf.ByteString
      getStateJsonBytes();
}
