// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/asset/asset.proto
// Protobuf Java Version: 4.28.3

package ink.asset.model;

public interface AssetRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.asset.model.AssetRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emoji = 1;</code>
   * @return The emoji.
   */
  java.lang.String getEmoji();
  /**
   * <code>string emoji = 1;</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();

  /**
   * <code>.ink.asset.model.AssetCategory category = 2;</code>
   * @return Whether the category field is set.
   */
  boolean hasCategory();
  /**
   * <code>.ink.asset.model.AssetCategory category = 2;</code>
   * @return The category.
   */
  ink.asset.model.AssetCategory getCategory();
  /**
   * <code>.ink.asset.model.AssetCategory category = 2;</code>
   */
  ink.asset.model.AssetCategoryOrBuilder getCategoryOrBuilder();

  /**
   * <pre>
   * "weapon_sword_01.glb"
   * </pre>
   *
   * <code>string mesh_path = 3;</code>
   * @return The meshPath.
   */
  java.lang.String getMeshPath();
  /**
   * <pre>
   * "weapon_sword_01.glb"
   * </pre>
   *
   * <code>string mesh_path = 3;</code>
   * @return The bytes for meshPath.
   */
  com.google.protobuf.ByteString
      getMeshPathBytes();

  /**
   * <pre>
   * "sword_1h"
   * </pre>
   *
   * <code>string anim_set_id = 4;</code>
   * @return The animSetId.
   */
  java.lang.String getAnimSetId();
  /**
   * <pre>
   * "sword_1h"
   * </pre>
   *
   * <code>string anim_set_id = 4;</code>
   * @return The bytes for animSetId.
   */
  com.google.protobuf.ByteString
      getAnimSetIdBytes();

  /**
   * <code>.ink.asset.model.VoiceRef voice_ref = 5;</code>
   * @return Whether the voiceRef field is set.
   */
  boolean hasVoiceRef();
  /**
   * <code>.ink.asset.model.VoiceRef voice_ref = 5;</code>
   * @return The voiceRef.
   */
  ink.asset.model.VoiceRef getVoiceRef();
  /**
   * <code>.ink.asset.model.VoiceRef voice_ref = 5;</code>
   */
  ink.asset.model.VoiceRefOrBuilder getVoiceRefOrBuilder();

  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 6;</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);
}
