// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/asset/asset.proto
// Protobuf Java Version: 4.28.3

package ink.asset.model;

/**
 * Protobuf type {@code ink.asset.model.VoiceRef}
 */
public final class VoiceRef extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ink.asset.model.VoiceRef)
    VoiceRefOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      VoiceRef.class.getName());
  }
  // Use VoiceRef.newBuilder() to construct.
  private VoiceRef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VoiceRef() {
    characterId_ = "";
    language_ = "";
    flacPath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ink.asset.model.Asset.internal_static_ink_asset_model_VoiceRef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ink.asset.model.Asset.internal_static_ink_asset_model_VoiceRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ink.asset.model.VoiceRef.class, ink.asset.model.VoiceRef.Builder.class);
  }

  public static final int CHARACTER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object characterId_ = "";
  /**
   * <pre>
   * "gandalf"
   * </pre>
   *
   * <code>string character_id = 1;</code>
   * @return The characterId.
   */
  @java.lang.Override
  public java.lang.String getCharacterId() {
    java.lang.Object ref = characterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      characterId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "gandalf"
   * </pre>
   *
   * <code>string character_id = 1;</code>
   * @return The bytes for characterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCharacterIdBytes() {
    java.lang.Object ref = characterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      characterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <pre>
   * "en", "he", "ar"
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "en", "he", "ar"
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLAC_PATH_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object flacPath_ = "";
  /**
   * <pre>
   * "voices/gandalf_en.flac"
   * </pre>
   *
   * <code>string flac_path = 3;</code>
   * @return The flacPath.
   */
  @java.lang.Override
  public java.lang.String getFlacPath() {
    java.lang.Object ref = flacPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flacPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "voices/gandalf_en.flac"
   * </pre>
   *
   * <code>string flac_path = 3;</code>
   * @return The bytes for flacPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlacPathBytes() {
    java.lang.Object ref = flacPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flacPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(characterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, characterId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flacPath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, flacPath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(characterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, characterId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flacPath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, flacPath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ink.asset.model.VoiceRef)) {
      return super.equals(obj);
    }
    ink.asset.model.VoiceRef other = (ink.asset.model.VoiceRef) obj;

    if (!getCharacterId()
        .equals(other.getCharacterId())) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getFlacPath()
        .equals(other.getFlacPath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHARACTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCharacterId().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + FLAC_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFlacPath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ink.asset.model.VoiceRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.asset.model.VoiceRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.asset.model.VoiceRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ink.asset.model.VoiceRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ink.asset.model.VoiceRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.asset.model.VoiceRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ink.asset.model.VoiceRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ink.asset.model.VoiceRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ink.asset.model.VoiceRef)
      ink.asset.model.VoiceRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ink.asset.model.Asset.internal_static_ink_asset_model_VoiceRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ink.asset.model.Asset.internal_static_ink_asset_model_VoiceRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ink.asset.model.VoiceRef.class, ink.asset.model.VoiceRef.Builder.class);
    }

    // Construct using ink.asset.model.VoiceRef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      characterId_ = "";
      language_ = "";
      flacPath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ink.asset.model.Asset.internal_static_ink_asset_model_VoiceRef_descriptor;
    }

    @java.lang.Override
    public ink.asset.model.VoiceRef getDefaultInstanceForType() {
      return ink.asset.model.VoiceRef.getDefaultInstance();
    }

    @java.lang.Override
    public ink.asset.model.VoiceRef build() {
      ink.asset.model.VoiceRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ink.asset.model.VoiceRef buildPartial() {
      ink.asset.model.VoiceRef result = new ink.asset.model.VoiceRef(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ink.asset.model.VoiceRef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.characterId_ = characterId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.flacPath_ = flacPath_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ink.asset.model.VoiceRef) {
        return mergeFrom((ink.asset.model.VoiceRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ink.asset.model.VoiceRef other) {
      if (other == ink.asset.model.VoiceRef.getDefaultInstance()) return this;
      if (!other.getCharacterId().isEmpty()) {
        characterId_ = other.characterId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getFlacPath().isEmpty()) {
        flacPath_ = other.flacPath_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              characterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              flacPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object characterId_ = "";
    /**
     * <pre>
     * "gandalf"
     * </pre>
     *
     * <code>string character_id = 1;</code>
     * @return The characterId.
     */
    public java.lang.String getCharacterId() {
      java.lang.Object ref = characterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        characterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "gandalf"
     * </pre>
     *
     * <code>string character_id = 1;</code>
     * @return The bytes for characterId.
     */
    public com.google.protobuf.ByteString
        getCharacterIdBytes() {
      java.lang.Object ref = characterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        characterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "gandalf"
     * </pre>
     *
     * <code>string character_id = 1;</code>
     * @param value The characterId to set.
     * @return This builder for chaining.
     */
    public Builder setCharacterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      characterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "gandalf"
     * </pre>
     *
     * <code>string character_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCharacterId() {
      characterId_ = getDefaultInstance().getCharacterId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "gandalf"
     * </pre>
     *
     * <code>string character_id = 1;</code>
     * @param value The bytes for characterId to set.
     * @return This builder for chaining.
     */
    public Builder setCharacterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      characterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <pre>
     * "en", "he", "ar"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "en", "he", "ar"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "en", "he", "ar"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "en", "he", "ar"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "en", "he", "ar"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object flacPath_ = "";
    /**
     * <pre>
     * "voices/gandalf_en.flac"
     * </pre>
     *
     * <code>string flac_path = 3;</code>
     * @return The flacPath.
     */
    public java.lang.String getFlacPath() {
      java.lang.Object ref = flacPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flacPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "voices/gandalf_en.flac"
     * </pre>
     *
     * <code>string flac_path = 3;</code>
     * @return The bytes for flacPath.
     */
    public com.google.protobuf.ByteString
        getFlacPathBytes() {
      java.lang.Object ref = flacPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flacPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "voices/gandalf_en.flac"
     * </pre>
     *
     * <code>string flac_path = 3;</code>
     * @param value The flacPath to set.
     * @return This builder for chaining.
     */
    public Builder setFlacPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      flacPath_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "voices/gandalf_en.flac"
     * </pre>
     *
     * <code>string flac_path = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlacPath() {
      flacPath_ = getDefaultInstance().getFlacPath();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "voices/gandalf_en.flac"
     * </pre>
     *
     * <code>string flac_path = 3;</code>
     * @param value The bytes for flacPath to set.
     * @return This builder for chaining.
     */
    public Builder setFlacPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      flacPath_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ink.asset.model.VoiceRef)
  }

  // @@protoc_insertion_point(class_scope:ink.asset.model.VoiceRef)
  private static final ink.asset.model.VoiceRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ink.asset.model.VoiceRef();
  }

  public static ink.asset.model.VoiceRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoiceRef>
      PARSER = new com.google.protobuf.AbstractParser<VoiceRef>() {
    @java.lang.Override
    public VoiceRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoiceRef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoiceRef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ink.asset.model.VoiceRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

