// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/event.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface AssetEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.AssetEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * equip, unequip, use, spawn, despawn
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * equip, unequip, use, spawn, despawn
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>.ink.model.AssetRef asset = 3;</code>
   * @return Whether the asset field is set.
   */
  boolean hasAsset();
  /**
   * <code>.ink.model.AssetRef asset = 3;</code>
   * @return The asset.
   */
  ink.java.model.AssetRef getAsset();
  /**
   * <code>.ink.model.AssetRef asset = 3;</code>
   */
  ink.java.model.AssetRefOrBuilder getAssetOrBuilder();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
