// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/calendar.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public final class Calendar {
  private Calendar() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Calendar.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_InkEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_InkEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ink/model/calendar.proto\022\tink.model\"\223\001" +
      "\n\010InkEvent\022\013\n\003uid\030\001 \001(\t\022\017\n\007summary\030\002 \001(\t" +
      "\022\023\n\013description\030\003 \001(\t\022\020\n\010dt_start\030\004 \001(\t\022" +
      "\016\n\006dt_end\030\005 \001(\t\022\020\n\010category\030\006 \001(\t\022\020\n\010loc" +
      "ation\030\007 \001(\t\022\016\n\006status\030\010 \001(\tB!\n\016ink.java." +
      "modelP\001\252\002\014Ink.Cs.Modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ink_model_InkEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_model_InkEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_InkEvent_descriptor,
        new java.lang.String[] { "Uid", "Summary", "Description", "DtStart", "DtEnd", "Category", "Location", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
