// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/table.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf enum {@code ink.model.CellType}
 */
public enum CellType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STRING = 0;</code>
   */
  STRING(0),
  /**
   * <code>INT = 1;</code>
   */
  INT(1),
  /**
   * <code>FLOAT = 2;</code>
   */
  FLOAT(2),
  /**
   * <code>BOOL = 3;</code>
   */
  BOOL(3),
  /**
   * <pre>
   * POI XLSX formula (e.g. "=D2+E2*F2")
   * </pre>
   *
   * <code>FORMULA = 4;</code>
   */
  FORMULA(4),
  /**
   * <pre>
   * Emoji category reference (resolved by EmojiAssetManifest)
   * </pre>
   *
   * <code>EMOJI = 5;</code>
   */
  EMOJI(5),
  /**
   * <pre>
   * Faker method placeholder (resolved by InkFakerEngine)
   * </pre>
   *
   * <code>FAKER = 6;</code>
   */
  FAKER(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      CellType.class.getName());
  }
  /**
   * <code>STRING = 0;</code>
   */
  public static final int STRING_VALUE = 0;
  /**
   * <code>INT = 1;</code>
   */
  public static final int INT_VALUE = 1;
  /**
   * <code>FLOAT = 2;</code>
   */
  public static final int FLOAT_VALUE = 2;
  /**
   * <code>BOOL = 3;</code>
   */
  public static final int BOOL_VALUE = 3;
  /**
   * <pre>
   * POI XLSX formula (e.g. "=D2+E2*F2")
   * </pre>
   *
   * <code>FORMULA = 4;</code>
   */
  public static final int FORMULA_VALUE = 4;
  /**
   * <pre>
   * Emoji category reference (resolved by EmojiAssetManifest)
   * </pre>
   *
   * <code>EMOJI = 5;</code>
   */
  public static final int EMOJI_VALUE = 5;
  /**
   * <pre>
   * Faker method placeholder (resolved by InkFakerEngine)
   * </pre>
   *
   * <code>FAKER = 6;</code>
   */
  public static final int FAKER_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CellType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CellType forNumber(int value) {
    switch (value) {
      case 0: return STRING;
      case 1: return INT;
      case 2: return FLOAT;
      case 3: return BOOL;
      case 4: return FORMULA;
      case 5: return EMOJI;
      case 6: return FAKER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CellType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CellType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CellType>() {
          public CellType findValueByNumber(int number) {
            return CellType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ink.java.model.Table.getDescriptor().getEnumTypes().get(0);
  }

  private static final CellType[] VALUES = values();

  public static CellType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CellType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ink.model.CellType)
}

