// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/structure.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf enum {@code ink.model.DiagramMode}
 */
public enum DiagramMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DIAGRAM_MODE_UNSPECIFIED = 0;</code>
   */
  DIAGRAM_MODE_UNSPECIFIED(0),
  /**
   * <code>ACTIVITY = 1;</code>
   */
  ACTIVITY(1),
  /**
   * <code>STATE = 2;</code>
   */
  STATE(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DiagramMode.class.getName());
  }
  /**
   * <code>DIAGRAM_MODE_UNSPECIFIED = 0;</code>
   */
  public static final int DIAGRAM_MODE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ACTIVITY = 1;</code>
   */
  public static final int ACTIVITY_VALUE = 1;
  /**
   * <code>STATE = 2;</code>
   */
  public static final int STATE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DiagramMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DiagramMode forNumber(int value) {
    switch (value) {
      case 0: return DIAGRAM_MODE_UNSPECIFIED;
      case 1: return ACTIVITY;
      case 2: return STATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DiagramMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DiagramMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DiagramMode>() {
          public DiagramMode findValueByNumber(int number) {
            return DiagramMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ink.java.model.StructureOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final DiagramMode[] VALUES = values();

  public static DiagramMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DiagramMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ink.model.DiagramMode)
}

