// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/faker.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public final class Faker {
  private Faker() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Faker.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_FakerConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_FakerConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_EmojiCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_EmojiCategory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ink/model/faker.proto\022\tink.model\"]\n\013Fa" +
      "kerConfig\022\014\n\004seed\030\001 \001(\003\022\016\n\006locale\030\002 \001(\t\022" +
      "\r\n\005count\030\003 \001(\005\022\r\n\005level\030\004 \001(\005\022\022\n\ncategor" +
      "ies\030\005 \003(\t\"r\n\rEmojiCategory\022\r\n\005emoji\030\001 \001(" +
      "\t\022\026\n\016faker_provider\030\002 \001(\t\022\024\n\014method_chai" +
      "n\030\003 \001(\t\022\021\n\trange_min\030\004 \001(\005\022\021\n\trange_max\030" +
      "\005 \001(\005B!\n\016ink.java.modelP\001\252\002\014Ink.Cs.Model" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ink_model_FakerConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_model_FakerConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_FakerConfig_descriptor,
        new java.lang.String[] { "Seed", "Locale", "Count", "Level", "Categories", });
    internal_static_ink_model_EmojiCategory_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ink_model_EmojiCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_EmojiCategory_descriptor,
        new java.lang.String[] { "Emoji", "FakerProvider", "MethodChain", "RangeMin", "RangeMax", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
