// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/event.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface InkTagEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.InkTagEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>repeated string tags = 2;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 2;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 2;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>string knot = 3;</code>
   * @return The knot.
   */
  java.lang.String getKnot();
  /**
   * <code>string knot = 3;</code>
   * @return The bytes for knot.
   */
  com.google.protobuf.ByteString
      getKnotBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * assets resolved from tags
   * </pre>
   *
   * <code>repeated .ink.model.AssetRef resolved_assets = 5;</code>
   */
  java.util.List<ink.java.model.AssetRef> 
      getResolvedAssetsList();
  /**
   * <pre>
   * assets resolved from tags
   * </pre>
   *
   * <code>repeated .ink.model.AssetRef resolved_assets = 5;</code>
   */
  ink.java.model.AssetRef getResolvedAssets(int index);
  /**
   * <pre>
   * assets resolved from tags
   * </pre>
   *
   * <code>repeated .ink.model.AssetRef resolved_assets = 5;</code>
   */
  int getResolvedAssetsCount();
  /**
   * <pre>
   * assets resolved from tags
   * </pre>
   *
   * <code>repeated .ink.model.AssetRef resolved_assets = 5;</code>
   */
  java.util.List<? extends ink.java.model.AssetRefOrBuilder> 
      getResolvedAssetsOrBuilderList();
  /**
   * <pre>
   * assets resolved from tags
   * </pre>
   *
   * <code>repeated .ink.model.AssetRef resolved_assets = 5;</code>
   */
  ink.java.model.AssetRefOrBuilder getResolvedAssetsOrBuilder(
      int index);
}
