// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/vcard.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface InkVCardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.InkVCard)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identification (§6.2)
   * </pre>
   *
   * <code>string uid = 1;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <pre>
   * Identification (§6.2)
   * </pre>
   *
   * <code>string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>.ink.model.VCardVersion version = 2;</code>
   * @return The enum numeric value on the wire for version.
   */
  int getVersionValue();
  /**
   * <code>.ink.model.VCardVersion version = 2;</code>
   * @return The version.
   */
  ink.java.model.VCardVersion getVersion();

  /**
   * <pre>
   * FN — display name
   * </pre>
   *
   * <code>string formatted_name = 3;</code>
   * @return The formattedName.
   */
  java.lang.String getFormattedName();
  /**
   * <pre>
   * FN — display name
   * </pre>
   *
   * <code>string formatted_name = 3;</code>
   * @return The bytes for formattedName.
   */
  com.google.protobuf.ByteString
      getFormattedNameBytes();

  /**
   * <pre>
   * N — structured name components
   * </pre>
   *
   * <code>.ink.model.VCardName name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * N — structured name components
   * </pre>
   *
   * <code>.ink.model.VCardName name = 4;</code>
   * @return The name.
   */
  ink.java.model.VCardName getName();
  /**
   * <pre>
   * N — structured name components
   * </pre>
   *
   * <code>.ink.model.VCardName name = 4;</code>
   */
  ink.java.model.VCardNameOrBuilder getNameOrBuilder();

  /**
   * <pre>
   * Communication (§6.4)
   * </pre>
   *
   * <code>repeated .ink.model.VCardEmail emails = 5;</code>
   */
  java.util.List<ink.java.model.VCardEmail> 
      getEmailsList();
  /**
   * <pre>
   * Communication (§6.4)
   * </pre>
   *
   * <code>repeated .ink.model.VCardEmail emails = 5;</code>
   */
  ink.java.model.VCardEmail getEmails(int index);
  /**
   * <pre>
   * Communication (§6.4)
   * </pre>
   *
   * <code>repeated .ink.model.VCardEmail emails = 5;</code>
   */
  int getEmailsCount();
  /**
   * <pre>
   * Communication (§6.4)
   * </pre>
   *
   * <code>repeated .ink.model.VCardEmail emails = 5;</code>
   */
  java.util.List<? extends ink.java.model.VCardEmailOrBuilder> 
      getEmailsOrBuilderList();
  /**
   * <pre>
   * Communication (§6.4)
   * </pre>
   *
   * <code>repeated .ink.model.VCardEmail emails = 5;</code>
   */
  ink.java.model.VCardEmailOrBuilder getEmailsOrBuilder(
      int index);

  /**
   * <code>repeated .ink.model.VCardTelephone telephones = 6;</code>
   */
  java.util.List<ink.java.model.VCardTelephone> 
      getTelephonesList();
  /**
   * <code>repeated .ink.model.VCardTelephone telephones = 6;</code>
   */
  ink.java.model.VCardTelephone getTelephones(int index);
  /**
   * <code>repeated .ink.model.VCardTelephone telephones = 6;</code>
   */
  int getTelephonesCount();
  /**
   * <code>repeated .ink.model.VCardTelephone telephones = 6;</code>
   */
  java.util.List<? extends ink.java.model.VCardTelephoneOrBuilder> 
      getTelephonesOrBuilderList();
  /**
   * <code>repeated .ink.model.VCardTelephone telephones = 6;</code>
   */
  ink.java.model.VCardTelephoneOrBuilder getTelephonesOrBuilder(
      int index);

  /**
   * <pre>
   * Address (§6.3)
   * </pre>
   *
   * <code>repeated .ink.model.VCardAddress addresses = 7;</code>
   */
  java.util.List<ink.java.model.VCardAddress> 
      getAddressesList();
  /**
   * <pre>
   * Address (§6.3)
   * </pre>
   *
   * <code>repeated .ink.model.VCardAddress addresses = 7;</code>
   */
  ink.java.model.VCardAddress getAddresses(int index);
  /**
   * <pre>
   * Address (§6.3)
   * </pre>
   *
   * <code>repeated .ink.model.VCardAddress addresses = 7;</code>
   */
  int getAddressesCount();
  /**
   * <pre>
   * Address (§6.3)
   * </pre>
   *
   * <code>repeated .ink.model.VCardAddress addresses = 7;</code>
   */
  java.util.List<? extends ink.java.model.VCardAddressOrBuilder> 
      getAddressesOrBuilderList();
  /**
   * <pre>
   * Address (§6.3)
   * </pre>
   *
   * <code>repeated .ink.model.VCardAddress addresses = 7;</code>
   */
  ink.java.model.VCardAddressOrBuilder getAddressesOrBuilder(
      int index);

  /**
   * <pre>
   * Organization (§6.6)
   * </pre>
   *
   * <code>.ink.model.VCardOrganization org = 8;</code>
   * @return Whether the org field is set.
   */
  boolean hasOrg();
  /**
   * <pre>
   * Organization (§6.6)
   * </pre>
   *
   * <code>.ink.model.VCardOrganization org = 8;</code>
   * @return The org.
   */
  ink.java.model.VCardOrganization getOrg();
  /**
   * <pre>
   * Organization (§6.6)
   * </pre>
   *
   * <code>.ink.model.VCardOrganization org = 8;</code>
   */
  ink.java.model.VCardOrganizationOrBuilder getOrgOrBuilder();

  /**
   * <pre>
   * Job title
   * </pre>
   *
   * <code>string title = 9;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Job title
   * </pre>
   *
   * <code>string title = 9;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Functional role
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <pre>
   * Functional role
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <pre>
   * Media (§6.2)
   * </pre>
   *
   * <code>.ink.model.VCardImage photo = 11;</code>
   * @return Whether the photo field is set.
   */
  boolean hasPhoto();
  /**
   * <pre>
   * Media (§6.2)
   * </pre>
   *
   * <code>.ink.model.VCardImage photo = 11;</code>
   * @return The photo.
   */
  ink.java.model.VCardImage getPhoto();
  /**
   * <pre>
   * Media (§6.2)
   * </pre>
   *
   * <code>.ink.model.VCardImage photo = 11;</code>
   */
  ink.java.model.VCardImageOrBuilder getPhotoOrBuilder();

  /**
   * <code>.ink.model.VCardImage logo = 12;</code>
   * @return Whether the logo field is set.
   */
  boolean hasLogo();
  /**
   * <code>.ink.model.VCardImage logo = 12;</code>
   * @return The logo.
   */
  ink.java.model.VCardImage getLogo();
  /**
   * <code>.ink.model.VCardImage logo = 12;</code>
   */
  ink.java.model.VCardImageOrBuilder getLogoOrBuilder();

  /**
   * <pre>
   * Web (§6.7)
   * </pre>
   *
   * <code>repeated string urls = 13;</code>
   * @return A list containing the urls.
   */
  java.util.List<java.lang.String>
      getUrlsList();
  /**
   * <pre>
   * Web (§6.7)
   * </pre>
   *
   * <code>repeated string urls = 13;</code>
   * @return The count of urls.
   */
  int getUrlsCount();
  /**
   * <pre>
   * Web (§6.7)
   * </pre>
   *
   * <code>repeated string urls = 13;</code>
   * @param index The index of the element to return.
   * @return The urls at the given index.
   */
  java.lang.String getUrls(int index);
  /**
   * <pre>
   * Web (§6.7)
   * </pre>
   *
   * <code>repeated string urls = 13;</code>
   * @param index The index of the value to return.
   * @return The bytes of the urls at the given index.
   */
  com.google.protobuf.ByteString
      getUrlsBytes(int index);

  /**
   * <pre>
   * Categories &amp; Notes (§6.7)
   * </pre>
   *
   * <code>repeated string categories = 14;</code>
   * @return A list containing the categories.
   */
  java.util.List<java.lang.String>
      getCategoriesList();
  /**
   * <pre>
   * Categories &amp; Notes (§6.7)
   * </pre>
   *
   * <code>repeated string categories = 14;</code>
   * @return The count of categories.
   */
  int getCategoriesCount();
  /**
   * <pre>
   * Categories &amp; Notes (§6.7)
   * </pre>
   *
   * <code>repeated string categories = 14;</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  java.lang.String getCategories(int index);
  /**
   * <pre>
   * Categories &amp; Notes (§6.7)
   * </pre>
   *
   * <code>repeated string categories = 14;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categories at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriesBytes(int index);

  /**
   * <code>string note = 15;</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <code>string note = 15;</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <pre>
   * Security (§6.8)
   * </pre>
   *
   * <code>string key = 16;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * Security (§6.8)
   * </pre>
   *
   * <code>string key = 16;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * Timestamps
   * </pre>
   *
   * <code>string rev = 17;</code>
   * @return The rev.
   */
  java.lang.String getRev();
  /**
   * <pre>
   * Timestamps
   * </pre>
   *
   * <code>string rev = 17;</code>
   * @return The bytes for rev.
   */
  com.google.protobuf.ByteString
      getRevBytes();

  /**
   * <pre>
   * ── Ink-specific extensions ────────────────────────────────────
   * </pre>
   *
   * <code>bool is_llm = 18;</code>
   * @return The isLlm.
   */
  boolean getIsLlm();

  /**
   * <pre>
   * ink roles: "edit", "view"
   * </pre>
   *
   * <code>repeated string roles = 19;</code>
   * @return A list containing the roles.
   */
  java.util.List<java.lang.String>
      getRolesList();
  /**
   * <pre>
   * ink roles: "edit", "view"
   * </pre>
   *
   * <code>repeated string roles = 19;</code>
   * @return The count of roles.
   */
  int getRolesCount();
  /**
   * <pre>
   * ink roles: "edit", "view"
   * </pre>
   *
   * <code>repeated string roles = 19;</code>
   * @param index The index of the element to return.
   * @return The roles at the given index.
   */
  java.lang.String getRoles(int index);
  /**
   * <pre>
   * ink roles: "edit", "view"
   * </pre>
   *
   * <code>repeated string roles = 19;</code>
   * @param index The index of the value to return.
   * @return The bytes of the roles at the given index.
   */
  com.google.protobuf.ByteString
      getRolesBytes(int index);

  /**
   * <pre>
   * domain/user/ filesystem path
   * </pre>
   *
   * <code>string folder_path = 20;</code>
   * @return The folderPath.
   */
  java.lang.String getFolderPath();
  /**
   * <pre>
   * domain/user/ filesystem path
   * </pre>
   *
   * <code>string folder_path = 20;</code>
   * @return The bytes for folderPath.
   */
  com.google.protobuf.ByteString
      getFolderPathBytes();

  /**
   * <pre>
   * mcp://model:jwt&#64;host:port/tool
   * </pre>
   *
   * <code>string mcp_uri = 21;</code>
   * @return The mcpUri.
   */
  java.lang.String getMcpUri();
  /**
   * <pre>
   * mcp://model:jwt&#64;host:port/tool
   * </pre>
   *
   * <code>string mcp_uri = 21;</code>
   * @return The bytes for mcpUri.
   */
  com.google.protobuf.ByteString
      getMcpUriBytes();

  /**
   * <pre>
   * Full jCard JSON (RFC 7095) for JWT embedding
   * </pre>
   *
   * <code>string jcard_json = 22;</code>
   * @return The jcardJson.
   */
  java.lang.String getJcardJson();
  /**
   * <pre>
   * Full jCard JSON (RFC 7095) for JWT embedding
   * </pre>
   *
   * <code>string jcard_json = 22;</code>
   * @return The bytes for jcardJson.
   */
  com.google.protobuf.ByteString
      getJcardJsonBytes();

  /**
   * <pre>
   * Custom X-* properties
   * </pre>
   *
   * <code>repeated .ink.model.VCardExtProperty ext_properties = 23;</code>
   */
  java.util.List<ink.java.model.VCardExtProperty> 
      getExtPropertiesList();
  /**
   * <pre>
   * Custom X-* properties
   * </pre>
   *
   * <code>repeated .ink.model.VCardExtProperty ext_properties = 23;</code>
   */
  ink.java.model.VCardExtProperty getExtProperties(int index);
  /**
   * <pre>
   * Custom X-* properties
   * </pre>
   *
   * <code>repeated .ink.model.VCardExtProperty ext_properties = 23;</code>
   */
  int getExtPropertiesCount();
  /**
   * <pre>
   * Custom X-* properties
   * </pre>
   *
   * <code>repeated .ink.model.VCardExtProperty ext_properties = 23;</code>
   */
  java.util.List<? extends ink.java.model.VCardExtPropertyOrBuilder> 
      getExtPropertiesOrBuilderList();
  /**
   * <pre>
   * Custom X-* properties
   * </pre>
   *
   * <code>repeated .ink.model.VCardExtProperty ext_properties = 23;</code>
   */
  ink.java.model.VCardExtPropertyOrBuilder getExtPropertiesOrBuilder(
      int index);

  /**
   * <pre>
   * Language &amp; Locale
   * </pre>
   *
   * <code>string language = 24;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * Language &amp; Locale
   * </pre>
   *
   * <code>string language = 24;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * TZ property (IANA timezone)
   * </pre>
   *
   * <code>string timezone = 25;</code>
   * @return The timezone.
   */
  java.lang.String getTimezone();
  /**
   * <pre>
   * TZ property (IANA timezone)
   * </pre>
   *
   * <code>string timezone = 25;</code>
   * @return The bytes for timezone.
   */
  com.google.protobuf.ByteString
      getTimezoneBytes();
}
