// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/event.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf enum {@code ink.model.LoadPriority}
 */
public enum LoadPriority
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOAD_PRIORITY_UNSPECIFIED = 0;</code>
   */
  LOAD_PRIORITY_UNSPECIFIED(0),
  /**
   * <code>IMMEDIATE = 1;</code>
   */
  IMMEDIATE(1),
  /**
   * <code>PRELOAD = 2;</code>
   */
  PRELOAD(2),
  /**
   * <code>LAZY = 3;</code>
   */
  LAZY(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      LoadPriority.class.getName());
  }
  /**
   * <code>LOAD_PRIORITY_UNSPECIFIED = 0;</code>
   */
  public static final int LOAD_PRIORITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>IMMEDIATE = 1;</code>
   */
  public static final int IMMEDIATE_VALUE = 1;
  /**
   * <code>PRELOAD = 2;</code>
   */
  public static final int PRELOAD_VALUE = 2;
  /**
   * <code>LAZY = 3;</code>
   */
  public static final int LAZY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LoadPriority valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LoadPriority forNumber(int value) {
    switch (value) {
      case 0: return LOAD_PRIORITY_UNSPECIFIED;
      case 1: return IMMEDIATE;
      case 2: return PRELOAD;
      case 3: return LAZY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LoadPriority>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LoadPriority> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LoadPriority>() {
          public LoadPriority findValueByNumber(int number) {
            return LoadPriority.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ink.java.model.Event.getDescriptor().getEnumTypes().get(1);
  }

  private static final LoadPriority[] VALUES = values();

  public static LoadPriority valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LoadPriority(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ink.model.LoadPriority)
}

