// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/mcp.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface McpToolsListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.McpToolsListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  java.util.List<ink.java.model.McpToolInfo> 
      getToolsList();
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  ink.java.model.McpToolInfo getTools(int index);
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  int getToolsCount();
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  java.util.List<? extends ink.java.model.McpToolInfoOrBuilder> 
      getToolsOrBuilderList();
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  ink.java.model.McpToolInfoOrBuilder getToolsOrBuilder(
      int index);
}
