// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/mcp.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf type {@code ink.model.McpToolsListResult}
 */
public final class McpToolsListResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ink.model.McpToolsListResult)
    McpToolsListResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      McpToolsListResult.class.getName());
  }
  // Use McpToolsListResult.newBuilder() to construct.
  private McpToolsListResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private McpToolsListResult() {
    tools_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ink.java.model.Mcp.internal_static_ink_model_McpToolsListResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ink.java.model.Mcp.internal_static_ink_model_McpToolsListResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ink.java.model.McpToolsListResult.class, ink.java.model.McpToolsListResult.Builder.class);
  }

  public static final int TOOLS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ink.java.model.McpToolInfo> tools_;
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ink.java.model.McpToolInfo> getToolsList() {
    return tools_;
  }
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ink.java.model.McpToolInfoOrBuilder> 
      getToolsOrBuilderList() {
    return tools_;
  }
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  @java.lang.Override
  public int getToolsCount() {
    return tools_.size();
  }
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  @java.lang.Override
  public ink.java.model.McpToolInfo getTools(int index) {
    return tools_.get(index);
  }
  /**
   * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
   */
  @java.lang.Override
  public ink.java.model.McpToolInfoOrBuilder getToolsOrBuilder(
      int index) {
    return tools_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tools_.size(); i++) {
      output.writeMessage(1, tools_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tools_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tools_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ink.java.model.McpToolsListResult)) {
      return super.equals(obj);
    }
    ink.java.model.McpToolsListResult other = (ink.java.model.McpToolsListResult) obj;

    if (!getToolsList()
        .equals(other.getToolsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getToolsCount() > 0) {
      hash = (37 * hash) + TOOLS_FIELD_NUMBER;
      hash = (53 * hash) + getToolsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ink.java.model.McpToolsListResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.McpToolsListResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.McpToolsListResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ink.java.model.McpToolsListResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ink.java.model.McpToolsListResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.McpToolsListResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ink.java.model.McpToolsListResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ink.model.McpToolsListResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ink.model.McpToolsListResult)
      ink.java.model.McpToolsListResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ink.java.model.Mcp.internal_static_ink_model_McpToolsListResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ink.java.model.Mcp.internal_static_ink_model_McpToolsListResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ink.java.model.McpToolsListResult.class, ink.java.model.McpToolsListResult.Builder.class);
    }

    // Construct using ink.java.model.McpToolsListResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (toolsBuilder_ == null) {
        tools_ = java.util.Collections.emptyList();
      } else {
        tools_ = null;
        toolsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ink.java.model.Mcp.internal_static_ink_model_McpToolsListResult_descriptor;
    }

    @java.lang.Override
    public ink.java.model.McpToolsListResult getDefaultInstanceForType() {
      return ink.java.model.McpToolsListResult.getDefaultInstance();
    }

    @java.lang.Override
    public ink.java.model.McpToolsListResult build() {
      ink.java.model.McpToolsListResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ink.java.model.McpToolsListResult buildPartial() {
      ink.java.model.McpToolsListResult result = new ink.java.model.McpToolsListResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ink.java.model.McpToolsListResult result) {
      if (toolsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tools_ = java.util.Collections.unmodifiableList(tools_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tools_ = tools_;
      } else {
        result.tools_ = toolsBuilder_.build();
      }
    }

    private void buildPartial0(ink.java.model.McpToolsListResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ink.java.model.McpToolsListResult) {
        return mergeFrom((ink.java.model.McpToolsListResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ink.java.model.McpToolsListResult other) {
      if (other == ink.java.model.McpToolsListResult.getDefaultInstance()) return this;
      if (toolsBuilder_ == null) {
        if (!other.tools_.isEmpty()) {
          if (tools_.isEmpty()) {
            tools_ = other.tools_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToolsIsMutable();
            tools_.addAll(other.tools_);
          }
          onChanged();
        }
      } else {
        if (!other.tools_.isEmpty()) {
          if (toolsBuilder_.isEmpty()) {
            toolsBuilder_.dispose();
            toolsBuilder_ = null;
            tools_ = other.tools_;
            bitField0_ = (bitField0_ & ~0x00000001);
            toolsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getToolsFieldBuilder() : null;
          } else {
            toolsBuilder_.addAllMessages(other.tools_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ink.java.model.McpToolInfo m =
                  input.readMessage(
                      ink.java.model.McpToolInfo.parser(),
                      extensionRegistry);
              if (toolsBuilder_ == null) {
                ensureToolsIsMutable();
                tools_.add(m);
              } else {
                toolsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ink.java.model.McpToolInfo> tools_ =
      java.util.Collections.emptyList();
    private void ensureToolsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tools_ = new java.util.ArrayList<ink.java.model.McpToolInfo>(tools_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ink.java.model.McpToolInfo, ink.java.model.McpToolInfo.Builder, ink.java.model.McpToolInfoOrBuilder> toolsBuilder_;

    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public java.util.List<ink.java.model.McpToolInfo> getToolsList() {
      if (toolsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tools_);
      } else {
        return toolsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public int getToolsCount() {
      if (toolsBuilder_ == null) {
        return tools_.size();
      } else {
        return toolsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public ink.java.model.McpToolInfo getTools(int index) {
      if (toolsBuilder_ == null) {
        return tools_.get(index);
      } else {
        return toolsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder setTools(
        int index, ink.java.model.McpToolInfo value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.set(index, value);
        onChanged();
      } else {
        toolsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder setTools(
        int index, ink.java.model.McpToolInfo.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.set(index, builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder addTools(ink.java.model.McpToolInfo value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.add(value);
        onChanged();
      } else {
        toolsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder addTools(
        int index, ink.java.model.McpToolInfo value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.add(index, value);
        onChanged();
      } else {
        toolsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder addTools(
        ink.java.model.McpToolInfo.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.add(builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder addTools(
        int index, ink.java.model.McpToolInfo.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.add(index, builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder addAllTools(
        java.lang.Iterable<? extends ink.java.model.McpToolInfo> values) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tools_);
        onChanged();
      } else {
        toolsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder clearTools() {
      if (toolsBuilder_ == null) {
        tools_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        toolsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public Builder removeTools(int index) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.remove(index);
        onChanged();
      } else {
        toolsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public ink.java.model.McpToolInfo.Builder getToolsBuilder(
        int index) {
      return getToolsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public ink.java.model.McpToolInfoOrBuilder getToolsOrBuilder(
        int index) {
      if (toolsBuilder_ == null) {
        return tools_.get(index);  } else {
        return toolsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public java.util.List<? extends ink.java.model.McpToolInfoOrBuilder> 
         getToolsOrBuilderList() {
      if (toolsBuilder_ != null) {
        return toolsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tools_);
      }
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public ink.java.model.McpToolInfo.Builder addToolsBuilder() {
      return getToolsFieldBuilder().addBuilder(
          ink.java.model.McpToolInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public ink.java.model.McpToolInfo.Builder addToolsBuilder(
        int index) {
      return getToolsFieldBuilder().addBuilder(
          index, ink.java.model.McpToolInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .ink.model.McpToolInfo tools = 1;</code>
     */
    public java.util.List<ink.java.model.McpToolInfo.Builder> 
         getToolsBuilderList() {
      return getToolsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ink.java.model.McpToolInfo, ink.java.model.McpToolInfo.Builder, ink.java.model.McpToolInfoOrBuilder> 
        getToolsFieldBuilder() {
      if (toolsBuilder_ == null) {
        toolsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ink.java.model.McpToolInfo, ink.java.model.McpToolInfo.Builder, ink.java.model.McpToolInfoOrBuilder>(
                tools_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tools_ = null;
      }
      return toolsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ink.model.McpToolsListResult)
  }

  // @@protoc_insertion_point(class_scope:ink.model.McpToolsListResult)
  private static final ink.java.model.McpToolsListResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ink.java.model.McpToolsListResult();
  }

  public static ink.java.model.McpToolsListResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<McpToolsListResult>
      PARSER = new com.google.protobuf.AbstractParser<McpToolsListResult>() {
    @java.lang.Override
    public McpToolsListResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<McpToolsListResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<McpToolsListResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ink.java.model.McpToolsListResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

