// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/principal.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public final class Principal {
  private Principal() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Principal.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_InkPrincipal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_InkPrincipal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_InkPrincipalInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_InkPrincipalInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ink/model/principal.proto\022\tink.model\"V" +
      "\n\014InkPrincipal\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\022\r\n\005roles\030\003 \003(\t\022\016\n\006is_llm\030\004 \001(\010\022\r\n\005email" +
      "\030\005 \001(\t\"\207\001\n\020InkPrincipalInfo\022\n\n\002id\030\001 \001(\t\022" +
      "\024\n\014display_name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n\004" +
      "role\030\004 \001(\t\022\016\n\006is_llm\030\005 \001(\010\022\023\n\013folder_pat" +
      "h\030\006 \001(\t\022\017\n\007mcp_uri\030\007 \001(\tB!\n\016ink.java.mod" +
      "elP\001\252\002\014Ink.Cs.Modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ink_model_InkPrincipal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_model_InkPrincipal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_InkPrincipal_descriptor,
        new java.lang.String[] { "Id", "Name", "Roles", "IsLlm", "Email", });
    internal_static_ink_model_InkPrincipalInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ink_model_InkPrincipalInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_InkPrincipalInfo_descriptor,
        new java.lang.String[] { "Id", "DisplayName", "Email", "Role", "IsLlm", "FolderPath", "McpUri", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
