// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/sillytavern.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public final class Sillytavern {
  private Sillytavern() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Sillytavern.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_StCharacterCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_StCharacterCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ink/model/sillytavern.proto\022\tink.model" +
      "\"\303\001\n\017StCharacterCard\022\014\n\004name\030\001 \001(\t\022\023\n\013de" +
      "scription\030\002 \001(\t\022\023\n\013personality\030\003 \001(\t\022\020\n\010" +
      "scenario\030\004 \001(\t\022\025\n\rfirst_message\030\005 \001(\t\022\023\n" +
      "\013mes_example\030\006 \001(\t\022\025\n\rsystem_prompt\030\007 \001(" +
      "\t\022\025\n\rcreator_notes\030\010 \001(\t\022\014\n\004tags\030\t \003(\tB!" +
      "\n\016ink.java.modelP\001\252\002\014Ink.Cs.Modelb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ink_model_StCharacterCard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_model_StCharacterCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_StCharacterCard_descriptor,
        new java.lang.String[] { "Name", "Description", "Personality", "Scenario", "FirstMessage", "MesExample", "SystemPrompt", "CreatorNotes", "Tags", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
