// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/sillytavern.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf type {@code ink.model.StCharacterCard}
 */
public final class StCharacterCard extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ink.model.StCharacterCard)
    StCharacterCardOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      StCharacterCard.class.getName());
  }
  // Use StCharacterCard.newBuilder() to construct.
  private StCharacterCard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StCharacterCard() {
    name_ = "";
    description_ = "";
    personality_ = "";
    scenario_ = "";
    firstMessage_ = "";
    mesExample_ = "";
    systemPrompt_ = "";
    creatorNotes_ = "";
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ink.java.model.Sillytavern.internal_static_ink_model_StCharacterCard_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ink.java.model.Sillytavern.internal_static_ink_model_StCharacterCard_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ink.java.model.StCharacterCard.class, ink.java.model.StCharacterCard.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONALITY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object personality_ = "";
  /**
   * <code>string personality = 3;</code>
   * @return The personality.
   */
  @java.lang.Override
  public java.lang.String getPersonality() {
    java.lang.Object ref = personality_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      personality_ = s;
      return s;
    }
  }
  /**
   * <code>string personality = 3;</code>
   * @return The bytes for personality.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPersonalityBytes() {
    java.lang.Object ref = personality_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      personality_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCENARIO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scenario_ = "";
  /**
   * <code>string scenario = 4;</code>
   * @return The scenario.
   */
  @java.lang.Override
  public java.lang.String getScenario() {
    java.lang.Object ref = scenario_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scenario_ = s;
      return s;
    }
  }
  /**
   * <code>string scenario = 4;</code>
   * @return The bytes for scenario.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScenarioBytes() {
    java.lang.Object ref = scenario_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scenario_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_MESSAGE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object firstMessage_ = "";
  /**
   * <code>string first_message = 5;</code>
   * @return The firstMessage.
   */
  @java.lang.Override
  public java.lang.String getFirstMessage() {
    java.lang.Object ref = firstMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string first_message = 5;</code>
   * @return The bytes for firstMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstMessageBytes() {
    java.lang.Object ref = firstMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MES_EXAMPLE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mesExample_ = "";
  /**
   * <code>string mes_example = 6;</code>
   * @return The mesExample.
   */
  @java.lang.Override
  public java.lang.String getMesExample() {
    java.lang.Object ref = mesExample_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mesExample_ = s;
      return s;
    }
  }
  /**
   * <code>string mes_example = 6;</code>
   * @return The bytes for mesExample.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMesExampleBytes() {
    java.lang.Object ref = mesExample_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mesExample_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEM_PROMPT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object systemPrompt_ = "";
  /**
   * <code>string system_prompt = 7;</code>
   * @return The systemPrompt.
   */
  @java.lang.Override
  public java.lang.String getSystemPrompt() {
    java.lang.Object ref = systemPrompt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemPrompt_ = s;
      return s;
    }
  }
  /**
   * <code>string system_prompt = 7;</code>
   * @return The bytes for systemPrompt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSystemPromptBytes() {
    java.lang.Object ref = systemPrompt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemPrompt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATOR_NOTES_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object creatorNotes_ = "";
  /**
   * <code>string creator_notes = 8;</code>
   * @return The creatorNotes.
   */
  @java.lang.Override
  public java.lang.String getCreatorNotes() {
    java.lang.Object ref = creatorNotes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creatorNotes_ = s;
      return s;
    }
  }
  /**
   * <code>string creator_notes = 8;</code>
   * @return The bytes for creatorNotes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatorNotesBytes() {
    java.lang.Object ref = creatorNotes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creatorNotes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string tags = 9;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string tags = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(personality_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, personality_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scenario_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, scenario_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, firstMessage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mesExample_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, mesExample_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(systemPrompt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, systemPrompt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(creatorNotes_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, creatorNotes_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, tags_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(personality_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, personality_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scenario_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, scenario_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, firstMessage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mesExample_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, mesExample_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(systemPrompt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, systemPrompt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(creatorNotes_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, creatorNotes_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ink.java.model.StCharacterCard)) {
      return super.equals(obj);
    }
    ink.java.model.StCharacterCard other = (ink.java.model.StCharacterCard) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getPersonality()
        .equals(other.getPersonality())) return false;
    if (!getScenario()
        .equals(other.getScenario())) return false;
    if (!getFirstMessage()
        .equals(other.getFirstMessage())) return false;
    if (!getMesExample()
        .equals(other.getMesExample())) return false;
    if (!getSystemPrompt()
        .equals(other.getSystemPrompt())) return false;
    if (!getCreatorNotes()
        .equals(other.getCreatorNotes())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + PERSONALITY_FIELD_NUMBER;
    hash = (53 * hash) + getPersonality().hashCode();
    hash = (37 * hash) + SCENARIO_FIELD_NUMBER;
    hash = (53 * hash) + getScenario().hashCode();
    hash = (37 * hash) + FIRST_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getFirstMessage().hashCode();
    hash = (37 * hash) + MES_EXAMPLE_FIELD_NUMBER;
    hash = (53 * hash) + getMesExample().hashCode();
    hash = (37 * hash) + SYSTEM_PROMPT_FIELD_NUMBER;
    hash = (53 * hash) + getSystemPrompt().hashCode();
    hash = (37 * hash) + CREATOR_NOTES_FIELD_NUMBER;
    hash = (53 * hash) + getCreatorNotes().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ink.java.model.StCharacterCard parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.StCharacterCard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.StCharacterCard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ink.java.model.StCharacterCard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ink.java.model.StCharacterCard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.StCharacterCard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ink.java.model.StCharacterCard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ink.model.StCharacterCard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ink.model.StCharacterCard)
      ink.java.model.StCharacterCardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ink.java.model.Sillytavern.internal_static_ink_model_StCharacterCard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ink.java.model.Sillytavern.internal_static_ink_model_StCharacterCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ink.java.model.StCharacterCard.class, ink.java.model.StCharacterCard.Builder.class);
    }

    // Construct using ink.java.model.StCharacterCard.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      description_ = "";
      personality_ = "";
      scenario_ = "";
      firstMessage_ = "";
      mesExample_ = "";
      systemPrompt_ = "";
      creatorNotes_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ink.java.model.Sillytavern.internal_static_ink_model_StCharacterCard_descriptor;
    }

    @java.lang.Override
    public ink.java.model.StCharacterCard getDefaultInstanceForType() {
      return ink.java.model.StCharacterCard.getDefaultInstance();
    }

    @java.lang.Override
    public ink.java.model.StCharacterCard build() {
      ink.java.model.StCharacterCard result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ink.java.model.StCharacterCard buildPartial() {
      ink.java.model.StCharacterCard result = new ink.java.model.StCharacterCard(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ink.java.model.StCharacterCard result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.personality_ = personality_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.scenario_ = scenario_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.firstMessage_ = firstMessage_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.mesExample_ = mesExample_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.systemPrompt_ = systemPrompt_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.creatorNotes_ = creatorNotes_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ink.java.model.StCharacterCard) {
        return mergeFrom((ink.java.model.StCharacterCard)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ink.java.model.StCharacterCard other) {
      if (other == ink.java.model.StCharacterCard.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPersonality().isEmpty()) {
        personality_ = other.personality_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getScenario().isEmpty()) {
        scenario_ = other.scenario_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getFirstMessage().isEmpty()) {
        firstMessage_ = other.firstMessage_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getMesExample().isEmpty()) {
        mesExample_ = other.mesExample_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getSystemPrompt().isEmpty()) {
        systemPrompt_ = other.systemPrompt_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getCreatorNotes().isEmpty()) {
        creatorNotes_ = other.creatorNotes_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000100;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              personality_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              scenario_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              firstMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              mesExample_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              systemPrompt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              creatorNotes_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object personality_ = "";
    /**
     * <code>string personality = 3;</code>
     * @return The personality.
     */
    public java.lang.String getPersonality() {
      java.lang.Object ref = personality_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personality_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string personality = 3;</code>
     * @return The bytes for personality.
     */
    public com.google.protobuf.ByteString
        getPersonalityBytes() {
      java.lang.Object ref = personality_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string personality = 3;</code>
     * @param value The personality to set.
     * @return This builder for chaining.
     */
    public Builder setPersonality(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      personality_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string personality = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPersonality() {
      personality_ = getDefaultInstance().getPersonality();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string personality = 3;</code>
     * @param value The bytes for personality to set.
     * @return This builder for chaining.
     */
    public Builder setPersonalityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      personality_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object scenario_ = "";
    /**
     * <code>string scenario = 4;</code>
     * @return The scenario.
     */
    public java.lang.String getScenario() {
      java.lang.Object ref = scenario_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scenario_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scenario = 4;</code>
     * @return The bytes for scenario.
     */
    public com.google.protobuf.ByteString
        getScenarioBytes() {
      java.lang.Object ref = scenario_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scenario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scenario = 4;</code>
     * @param value The scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenario(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scenario_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string scenario = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScenario() {
      scenario_ = getDefaultInstance().getScenario();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string scenario = 4;</code>
     * @param value The bytes for scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenarioBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scenario_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object firstMessage_ = "";
    /**
     * <code>string first_message = 5;</code>
     * @return The firstMessage.
     */
    public java.lang.String getFirstMessage() {
      java.lang.Object ref = firstMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string first_message = 5;</code>
     * @return The bytes for firstMessage.
     */
    public com.google.protobuf.ByteString
        getFirstMessageBytes() {
      java.lang.Object ref = firstMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string first_message = 5;</code>
     * @param value The firstMessage to set.
     * @return This builder for chaining.
     */
    public Builder setFirstMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      firstMessage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string first_message = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstMessage() {
      firstMessage_ = getDefaultInstance().getFirstMessage();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string first_message = 5;</code>
     * @param value The bytes for firstMessage to set.
     * @return This builder for chaining.
     */
    public Builder setFirstMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      firstMessage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object mesExample_ = "";
    /**
     * <code>string mes_example = 6;</code>
     * @return The mesExample.
     */
    public java.lang.String getMesExample() {
      java.lang.Object ref = mesExample_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mesExample_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mes_example = 6;</code>
     * @return The bytes for mesExample.
     */
    public com.google.protobuf.ByteString
        getMesExampleBytes() {
      java.lang.Object ref = mesExample_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mesExample_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mes_example = 6;</code>
     * @param value The mesExample to set.
     * @return This builder for chaining.
     */
    public Builder setMesExample(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mesExample_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string mes_example = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMesExample() {
      mesExample_ = getDefaultInstance().getMesExample();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string mes_example = 6;</code>
     * @param value The bytes for mesExample to set.
     * @return This builder for chaining.
     */
    public Builder setMesExampleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mesExample_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object systemPrompt_ = "";
    /**
     * <code>string system_prompt = 7;</code>
     * @return The systemPrompt.
     */
    public java.lang.String getSystemPrompt() {
      java.lang.Object ref = systemPrompt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemPrompt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string system_prompt = 7;</code>
     * @return The bytes for systemPrompt.
     */
    public com.google.protobuf.ByteString
        getSystemPromptBytes() {
      java.lang.Object ref = systemPrompt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemPrompt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string system_prompt = 7;</code>
     * @param value The systemPrompt to set.
     * @return This builder for chaining.
     */
    public Builder setSystemPrompt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      systemPrompt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string system_prompt = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemPrompt() {
      systemPrompt_ = getDefaultInstance().getSystemPrompt();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string system_prompt = 7;</code>
     * @param value The bytes for systemPrompt to set.
     * @return This builder for chaining.
     */
    public Builder setSystemPromptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      systemPrompt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object creatorNotes_ = "";
    /**
     * <code>string creator_notes = 8;</code>
     * @return The creatorNotes.
     */
    public java.lang.String getCreatorNotes() {
      java.lang.Object ref = creatorNotes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creatorNotes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creator_notes = 8;</code>
     * @return The bytes for creatorNotes.
     */
    public com.google.protobuf.ByteString
        getCreatorNotesBytes() {
      java.lang.Object ref = creatorNotes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creatorNotes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creator_notes = 8;</code>
     * @param value The creatorNotes to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorNotes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      creatorNotes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string creator_notes = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatorNotes() {
      creatorNotes_ = getDefaultInstance().getCreatorNotes();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string creator_notes = 8;</code>
     * @param value The bytes for creatorNotes to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      creatorNotes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tags = 9;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ink.model.StCharacterCard)
  }

  // @@protoc_insertion_point(class_scope:ink.model.StCharacterCard)
  private static final ink.java.model.StCharacterCard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ink.java.model.StCharacterCard();
  }

  public static ink.java.model.StCharacterCard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StCharacterCard>
      PARSER = new com.google.protobuf.AbstractParser<StCharacterCard>() {
    @java.lang.Override
    public StCharacterCard parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StCharacterCard> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StCharacterCard> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ink.java.model.StCharacterCard getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

