// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/debug.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface StepResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.StepResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>bool can_continue = 2;</code>
   * @return The canContinue.
   */
  boolean getCanContinue();

  /**
   * <code>repeated .ink.model.Choice choices = 3;</code>
   */
  java.util.List<ink.java.model.Choice> 
      getChoicesList();
  /**
   * <code>repeated .ink.model.Choice choices = 3;</code>
   */
  ink.java.model.Choice getChoices(int index);
  /**
   * <code>repeated .ink.model.Choice choices = 3;</code>
   */
  int getChoicesCount();
  /**
   * <code>repeated .ink.model.Choice choices = 3;</code>
   */
  java.util.List<? extends ink.java.model.ChoiceOrBuilder> 
      getChoicesOrBuilderList();
  /**
   * <code>repeated .ink.model.Choice choices = 3;</code>
   */
  ink.java.model.ChoiceOrBuilder getChoicesOrBuilder(
      int index);

  /**
   * <code>repeated string tags = 4;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 4;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>.ink.model.Breakpoint hit_breakpoint = 5;</code>
   * @return Whether the hitBreakpoint field is set.
   */
  boolean hasHitBreakpoint();
  /**
   * <code>.ink.model.Breakpoint hit_breakpoint = 5;</code>
   * @return The hitBreakpoint.
   */
  ink.java.model.Breakpoint getHitBreakpoint();
  /**
   * <code>.ink.model.Breakpoint hit_breakpoint = 5;</code>
   */
  ink.java.model.BreakpointOrBuilder getHitBreakpointOrBuilder();

  /**
   * <code>map&lt;string, .ink.model.WatchChange&gt; watch_changes = 6;</code>
   */
  int getWatchChangesCount();
  /**
   * <code>map&lt;string, .ink.model.WatchChange&gt; watch_changes = 6;</code>
   */
  boolean containsWatchChanges(
      java.lang.String key);
  /**
   * Use {@link #getWatchChangesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, ink.java.model.WatchChange>
  getWatchChanges();
  /**
   * <code>map&lt;string, .ink.model.WatchChange&gt; watch_changes = 6;</code>
   */
  java.util.Map<java.lang.String, ink.java.model.WatchChange>
  getWatchChangesMap();
  /**
   * <code>map&lt;string, .ink.model.WatchChange&gt; watch_changes = 6;</code>
   */
  /* nullable */
ink.java.model.WatchChange getWatchChangesOrDefault(
      java.lang.String key,
      /* nullable */
ink.java.model.WatchChange defaultValue);
  /**
   * <code>map&lt;string, .ink.model.WatchChange&gt; watch_changes = 6;</code>
   */
  ink.java.model.WatchChange getWatchChangesOrThrow(
      java.lang.String key);

  /**
   * <code>int32 step_number = 7;</code>
   * @return The stepNumber.
   */
  int getStepNumber();

  /**
   * <code>bool is_paused = 8;</code>
   * @return The isPaused.
   */
  boolean getIsPaused();
}
