// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/table.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public final class Table {
  private Table() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Table.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_MdCell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_MdCell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_MdRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_MdRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_MdRow_CellsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_MdRow_CellsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_model_MdTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_model_MdTable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ink/model/table.proto\022\tink.model\"^\n\006Md" +
      "Cell\022\r\n\005value\030\001 \001(\t\022\017\n\007formula\030\002 \001(\t\022\021\n\t" +
      "evaluated\030\003 \001(\t\022!\n\004type\030\004 \001(\0162\023.ink.mode" +
      "l.CellType\"t\n\005MdRow\022*\n\005cells\030\001 \003(\0132\033.ink" +
      ".model.MdRow.CellsEntry\032?\n\nCellsEntry\022\013\n" +
      "\003key\030\001 \001(\t\022 \n\005value\030\002 \001(\0132\021.ink.model.Md" +
      "Cell:\0028\001\"H\n\007MdTable\022\014\n\004name\030\001 \001(\t\022\017\n\007col" +
      "umns\030\002 \003(\t\022\036\n\004rows\030\003 \003(\0132\020.ink.model.MdR" +
      "ow*W\n\010CellType\022\n\n\006STRING\020\000\022\007\n\003INT\020\001\022\t\n\005F" +
      "LOAT\020\002\022\010\n\004BOOL\020\003\022\013\n\007FORMULA\020\004\022\t\n\005EMOJI\020\005" +
      "\022\t\n\005FAKER\020\006B!\n\016ink.java.modelP\001\252\002\014Ink.Cs" +
      ".Modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ink_model_MdCell_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_model_MdCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_MdCell_descriptor,
        new java.lang.String[] { "Value", "Formula", "Evaluated", "Type", });
    internal_static_ink_model_MdRow_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ink_model_MdRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_MdRow_descriptor,
        new java.lang.String[] { "Cells", });
    internal_static_ink_model_MdRow_CellsEntry_descriptor =
      internal_static_ink_model_MdRow_descriptor.getNestedTypes().get(0);
    internal_static_ink_model_MdRow_CellsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_MdRow_CellsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ink_model_MdTable_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ink_model_MdTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_model_MdTable_descriptor,
        new java.lang.String[] { "Name", "Columns", "Rows", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
