// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/vcard.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface VCardEmailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.VCardEmail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ink.model.EmailType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ink.model.EmailType type = 1;</code>
   * @return The type.
   */
  ink.java.model.EmailType getType();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>bool is_preferred = 3;</code>
   * @return The isPreferred.
   */
  boolean getIsPreferred();
}
