// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/vcard.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface VCardImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.VCardImage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * URL to image
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * URL to image
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * MIME type (image/png, image/jpeg)
   * </pre>
   *
   * <code>string media_type = 2;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <pre>
   * MIME type (image/png, image/jpeg)
   * </pre>
   *
   * <code>string media_type = 2;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <pre>
   * Inline binary data (base64 in jCard)
   * </pre>
   *
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
