// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/debug.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf type {@code ink.model.VisitEntry}
 */
public final class VisitEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ink.model.VisitEntry)
    VisitEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      VisitEntry.class.getName());
  }
  // Use VisitEntry.newBuilder() to construct.
  private VisitEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VisitEntry() {
    text_ = "";
    variablesChanged_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ink.java.model.Debug.internal_static_ink_model_VisitEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ink.java.model.Debug.internal_static_ink_model_VisitEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ink.java.model.VisitEntry.class, ink.java.model.VisitEntry.Builder.class);
  }

  public static final int STEP_FIELD_NUMBER = 1;
  private int step_ = 0;
  /**
   * <code>int32 step = 1;</code>
   * @return The step.
   */
  @java.lang.Override
  public int getStep() {
    return step_;
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHOICES_MADE_FIELD_NUMBER = 3;
  private int choicesMade_ = 0;
  /**
   * <code>int32 choices_made = 3;</code>
   * @return The choicesMade.
   */
  @java.lang.Override
  public int getChoicesMade() {
    return choicesMade_;
  }

  public static final int VARIABLES_CHANGED_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList variablesChanged_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string variables_changed = 4;</code>
   * @return A list containing the variablesChanged.
   */
  public com.google.protobuf.ProtocolStringList
      getVariablesChangedList() {
    return variablesChanged_;
  }
  /**
   * <code>repeated string variables_changed = 4;</code>
   * @return The count of variablesChanged.
   */
  public int getVariablesChangedCount() {
    return variablesChanged_.size();
  }
  /**
   * <code>repeated string variables_changed = 4;</code>
   * @param index The index of the element to return.
   * @return The variablesChanged at the given index.
   */
  public java.lang.String getVariablesChanged(int index) {
    return variablesChanged_.get(index);
  }
  /**
   * <code>repeated string variables_changed = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the variablesChanged at the given index.
   */
  public com.google.protobuf.ByteString
      getVariablesChangedBytes(int index) {
    return variablesChanged_.getByteString(index);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (step_ != 0) {
      output.writeInt32(1, step_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, text_);
    }
    if (choicesMade_ != 0) {
      output.writeInt32(3, choicesMade_);
    }
    for (int i = 0; i < variablesChanged_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, variablesChanged_.getRaw(i));
    }
    if (timestamp_ != 0L) {
      output.writeInt64(5, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (step_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, step_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, text_);
    }
    if (choicesMade_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, choicesMade_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < variablesChanged_.size(); i++) {
        dataSize += computeStringSizeNoTag(variablesChanged_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getVariablesChangedList().size();
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ink.java.model.VisitEntry)) {
      return super.equals(obj);
    }
    ink.java.model.VisitEntry other = (ink.java.model.VisitEntry) obj;

    if (getStep()
        != other.getStep()) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (getChoicesMade()
        != other.getChoicesMade()) return false;
    if (!getVariablesChangedList()
        .equals(other.getVariablesChangedList())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STEP_FIELD_NUMBER;
    hash = (53 * hash) + getStep();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + CHOICES_MADE_FIELD_NUMBER;
    hash = (53 * hash) + getChoicesMade();
    if (getVariablesChangedCount() > 0) {
      hash = (37 * hash) + VARIABLES_CHANGED_FIELD_NUMBER;
      hash = (53 * hash) + getVariablesChangedList().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ink.java.model.VisitEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.VisitEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.VisitEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.VisitEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.VisitEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.java.model.VisitEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.java.model.VisitEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.VisitEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ink.java.model.VisitEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ink.java.model.VisitEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ink.java.model.VisitEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.java.model.VisitEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ink.java.model.VisitEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ink.model.VisitEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ink.model.VisitEntry)
      ink.java.model.VisitEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ink.java.model.Debug.internal_static_ink_model_VisitEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ink.java.model.Debug.internal_static_ink_model_VisitEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ink.java.model.VisitEntry.class, ink.java.model.VisitEntry.Builder.class);
    }

    // Construct using ink.java.model.VisitEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      step_ = 0;
      text_ = "";
      choicesMade_ = 0;
      variablesChanged_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ink.java.model.Debug.internal_static_ink_model_VisitEntry_descriptor;
    }

    @java.lang.Override
    public ink.java.model.VisitEntry getDefaultInstanceForType() {
      return ink.java.model.VisitEntry.getDefaultInstance();
    }

    @java.lang.Override
    public ink.java.model.VisitEntry build() {
      ink.java.model.VisitEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ink.java.model.VisitEntry buildPartial() {
      ink.java.model.VisitEntry result = new ink.java.model.VisitEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ink.java.model.VisitEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.step_ = step_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.text_ = text_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.choicesMade_ = choicesMade_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        variablesChanged_.makeImmutable();
        result.variablesChanged_ = variablesChanged_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ink.java.model.VisitEntry) {
        return mergeFrom((ink.java.model.VisitEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ink.java.model.VisitEntry other) {
      if (other == ink.java.model.VisitEntry.getDefaultInstance()) return this;
      if (other.getStep() != 0) {
        setStep(other.getStep());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getChoicesMade() != 0) {
        setChoicesMade(other.getChoicesMade());
      }
      if (!other.variablesChanged_.isEmpty()) {
        if (variablesChanged_.isEmpty()) {
          variablesChanged_ = other.variablesChanged_;
          bitField0_ |= 0x00000008;
        } else {
          ensureVariablesChangedIsMutable();
          variablesChanged_.addAll(other.variablesChanged_);
        }
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              step_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              choicesMade_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureVariablesChangedIsMutable();
              variablesChanged_.add(s);
              break;
            } // case 34
            case 40: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int step_ ;
    /**
     * <code>int32 step = 1;</code>
     * @return The step.
     */
    @java.lang.Override
    public int getStep() {
      return step_;
    }
    /**
     * <code>int32 step = 1;</code>
     * @param value The step to set.
     * @return This builder for chaining.
     */
    public Builder setStep(int value) {

      step_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 step = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStep() {
      bitField0_ = (bitField0_ & ~0x00000001);
      step_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 2;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 2;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int choicesMade_ ;
    /**
     * <code>int32 choices_made = 3;</code>
     * @return The choicesMade.
     */
    @java.lang.Override
    public int getChoicesMade() {
      return choicesMade_;
    }
    /**
     * <code>int32 choices_made = 3;</code>
     * @param value The choicesMade to set.
     * @return This builder for chaining.
     */
    public Builder setChoicesMade(int value) {

      choicesMade_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 choices_made = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChoicesMade() {
      bitField0_ = (bitField0_ & ~0x00000004);
      choicesMade_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList variablesChanged_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureVariablesChangedIsMutable() {
      if (!variablesChanged_.isModifiable()) {
        variablesChanged_ = new com.google.protobuf.LazyStringArrayList(variablesChanged_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @return A list containing the variablesChanged.
     */
    public com.google.protobuf.ProtocolStringList
        getVariablesChangedList() {
      variablesChanged_.makeImmutable();
      return variablesChanged_;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @return The count of variablesChanged.
     */
    public int getVariablesChangedCount() {
      return variablesChanged_.size();
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param index The index of the element to return.
     * @return The variablesChanged at the given index.
     */
    public java.lang.String getVariablesChanged(int index) {
      return variablesChanged_.get(index);
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the variablesChanged at the given index.
     */
    public com.google.protobuf.ByteString
        getVariablesChangedBytes(int index) {
      return variablesChanged_.getByteString(index);
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param index The index to set the value at.
     * @param value The variablesChanged to set.
     * @return This builder for chaining.
     */
    public Builder setVariablesChanged(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureVariablesChangedIsMutable();
      variablesChanged_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param value The variablesChanged to add.
     * @return This builder for chaining.
     */
    public Builder addVariablesChanged(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureVariablesChangedIsMutable();
      variablesChanged_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param values The variablesChanged to add.
     * @return This builder for chaining.
     */
    public Builder addAllVariablesChanged(
        java.lang.Iterable<java.lang.String> values) {
      ensureVariablesChangedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, variablesChanged_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVariablesChanged() {
      variablesChanged_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string variables_changed = 4;</code>
     * @param value The bytes of the variablesChanged to add.
     * @return This builder for chaining.
     */
    public Builder addVariablesChangedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureVariablesChangedIsMutable();
      variablesChanged_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ink.model.VisitEntry)
  }

  // @@protoc_insertion_point(class_scope:ink.model.VisitEntry)
  private static final ink.java.model.VisitEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ink.java.model.VisitEntry();
  }

  public static ink.java.model.VisitEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VisitEntry>
      PARSER = new com.google.protobuf.AbstractParser<VisitEntry>() {
    @java.lang.Override
    public VisitEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VisitEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VisitEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ink.java.model.VisitEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

