// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/asset.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface VoiceRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.VoiceRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "gandalf"
   * </pre>
   *
   * <code>string character_id = 1;</code>
   * @return The characterId.
   */
  java.lang.String getCharacterId();
  /**
   * <pre>
   * "gandalf"
   * </pre>
   *
   * <code>string character_id = 1;</code>
   * @return The bytes for characterId.
   */
  com.google.protobuf.ByteString
      getCharacterIdBytes();

  /**
   * <pre>
   * "en", "he", "ar"
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * "en", "he", "ar"
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * "voices/gandalf_en.flac"
   * </pre>
   *
   * <code>string flac_path = 3;</code>
   * @return The flacPath.
   */
  java.lang.String getFlacPath();
  /**
   * <pre>
   * "voices/gandalf_en.flac"
   * </pre>
   *
   * <code>string flac_path = 3;</code>
   * @return The bytes for flacPath.
   */
  com.google.protobuf.ByteString
      getFlacPathBytes();
}
