// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/ical.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

/**
 * Protobuf enum {@code ink.model.Weekday}
 */
public enum Weekday
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WEEKDAY_UNSPECIFIED = 0;</code>
   */
  WEEKDAY_UNSPECIFIED(0),
  /**
   * <code>MO = 1;</code>
   */
  MO(1),
  /**
   * <code>TU = 2;</code>
   */
  TU(2),
  /**
   * <code>WE = 3;</code>
   */
  WE(3),
  /**
   * <code>TH = 4;</code>
   */
  TH(4),
  /**
   * <code>FR = 5;</code>
   */
  FR(5),
  /**
   * <code>SA = 6;</code>
   */
  SA(6),
  /**
   * <code>SU = 7;</code>
   */
  SU(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Weekday.class.getName());
  }
  /**
   * <code>WEEKDAY_UNSPECIFIED = 0;</code>
   */
  public static final int WEEKDAY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MO = 1;</code>
   */
  public static final int MO_VALUE = 1;
  /**
   * <code>TU = 2;</code>
   */
  public static final int TU_VALUE = 2;
  /**
   * <code>WE = 3;</code>
   */
  public static final int WE_VALUE = 3;
  /**
   * <code>TH = 4;</code>
   */
  public static final int TH_VALUE = 4;
  /**
   * <code>FR = 5;</code>
   */
  public static final int FR_VALUE = 5;
  /**
   * <code>SA = 6;</code>
   */
  public static final int SA_VALUE = 6;
  /**
   * <code>SU = 7;</code>
   */
  public static final int SU_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Weekday valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Weekday forNumber(int value) {
    switch (value) {
      case 0: return WEEKDAY_UNSPECIFIED;
      case 1: return MO;
      case 2: return TU;
      case 3: return WE;
      case 4: return TH;
      case 5: return FR;
      case 6: return SA;
      case 7: return SU;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Weekday>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Weekday> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Weekday>() {
          public Weekday findValueByNumber(int number) {
            return Weekday.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ink.java.model.Ical.getDescriptor().getEnumTypes().get(5);
  }

  private static final Weekday[] VALUES = values();

  public static Weekday valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Weekday(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ink.model.Weekday)
}

