// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/model/ical.proto
// Protobuf Java Version: 4.28.3

package ink.java.model;

public interface WeekdayNumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.model.WeekdayNum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * -1 = last, 1 = first, etc. (0 = every)
   * </pre>
   *
   * <code>int32 ordinal = 1;</code>
   * @return The ordinal.
   */
  int getOrdinal();

  /**
   * <code>.ink.model.Weekday day = 2;</code>
   * @return The enum numeric value on the wire for day.
   */
  int getDayValue();
  /**
   * <code>.ink.model.Weekday day = 2;</code>
   * @return The day.
   */
  ink.java.model.Weekday getDay();
}
