// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/debug/debug.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.debug.model;

@kotlin.jvm.JvmName("-initializestepResult")
public inline fun stepResult(block: ink.debug.model.StepResultKt.Dsl.() -> kotlin.Unit): ink.debug.model.StepResult =
  ink.debug.model.StepResultKt.Dsl._create(ink.debug.model.StepResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.debug.model.StepResult`
 */
public object StepResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.debug.model.StepResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.debug.model.StepResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.debug.model.StepResult = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.text
      @JvmName("setText")
      set(value) {
        _builder.text = value
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `bool can_continue = 2;`
     */
    public var canContinue: kotlin.Boolean
      @JvmName("getCanContinue")
      get() = _builder.canContinue
      @JvmName("setCanContinue")
      set(value) {
        _builder.canContinue = value
      }
    /**
     * `bool can_continue = 2;`
     */
    public fun clearCanContinue() {
      _builder.clearCanContinue()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChoicesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     */
     public val choices: com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.choicesList
      )
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     * @param value The choices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChoices")
    public fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.add(value: ink.story.model.Choice) {
      _builder.addChoices(value)
    }
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     * @param value The choices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChoices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.plusAssign(value: ink.story.model.Choice) {
      add(value)
    }
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     * @param values The choices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChoices")
    public fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.addAll(values: kotlin.collections.Iterable<ink.story.model.Choice>) {
      _builder.addAllChoices(values)
    }
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     * @param values The choices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChoices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.plusAssign(values: kotlin.collections.Iterable<ink.story.model.Choice>) {
      addAll(values)
    }
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     * @param index The index to set the value at.
     * @param value The choices to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChoices")
    public operator fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.set(index: kotlin.Int, value: ink.story.model.Choice) {
      _builder.setChoices(index, value)
    }
    /**
     * `repeated .ink.story.model.Choice choices = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChoices")
    public fun com.google.protobuf.kotlin.DslList<ink.story.model.Choice, ChoicesProxy>.clear() {
      _builder.clearChoices()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tags = 4;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.tagsList
      )
    /**
     * `repeated string tags = 4;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * `repeated string tags = 4;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tags = 4;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * `repeated string tags = 4;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tags = 4;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * `repeated string tags = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }
    /**
     * `.ink.debug.model.Breakpoint hit_breakpoint = 5;`
     */
    public var hitBreakpoint: ink.debug.model.Breakpoint
      @JvmName("getHitBreakpoint")
      get() = _builder.hitBreakpoint
      @JvmName("setHitBreakpoint")
      set(value) {
        _builder.hitBreakpoint = value
      }
    /**
     * `.ink.debug.model.Breakpoint hit_breakpoint = 5;`
     */
    public fun clearHitBreakpoint() {
      _builder.clearHitBreakpoint()
    }
    /**
     * `.ink.debug.model.Breakpoint hit_breakpoint = 5;`
     * @return Whether the hitBreakpoint field is set.
     */
    public fun hasHitBreakpoint(): kotlin.Boolean {
      return _builder.hasHitBreakpoint()
    }
    public val StepResultKt.Dsl.hitBreakpointOrNull: ink.debug.model.Breakpoint?
      get() = _builder.hitBreakpointOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WatchChangesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
     public val watchChanges: com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getWatchChangesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.watchChangesMap
      )
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
    @JvmName("putWatchChanges")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      .put(key: kotlin.String, value: ink.debug.model.WatchChange) {
         _builder.putWatchChanges(key, value)
       }
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setWatchChanges")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      .set(key: kotlin.String, value: ink.debug.model.WatchChange) {
         put(key, value)
       }
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeWatchChanges")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      .remove(key: kotlin.String) {
         _builder.removeWatchChanges(key)
       }
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllWatchChanges")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, ink.debug.model.WatchChange>) {
         _builder.putAllWatchChanges(map)
       }
    /**
     * `map<string, .ink.debug.model.WatchChange> watch_changes = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearWatchChanges")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.debug.model.WatchChange, WatchChangesProxy>
      .clear() {
         _builder.clearWatchChanges()
       }

    /**
     * `int32 step_number = 7;`
     */
    public var stepNumber: kotlin.Int
      @JvmName("getStepNumber")
      get() = _builder.stepNumber
      @JvmName("setStepNumber")
      set(value) {
        _builder.stepNumber = value
      }
    /**
     * `int32 step_number = 7;`
     */
    public fun clearStepNumber() {
      _builder.clearStepNumber()
    }

    /**
     * `bool is_paused = 8;`
     */
    public var isPaused: kotlin.Boolean
      @JvmName("getIsPaused")
      get() = _builder.isPaused
      @JvmName("setIsPaused")
      set(value) {
        _builder.isPaused = value
      }
    /**
     * `bool is_paused = 8;`
     */
    public fun clearIsPaused() {
      _builder.clearIsPaused()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.debug.model.StepResult.copy(block: `ink.debug.model`.StepResultKt.Dsl.() -> kotlin.Unit): ink.debug.model.StepResult =
  `ink.debug.model`.StepResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ink.debug.model.StepResultOrBuilder.hitBreakpointOrNull: ink.debug.model.Breakpoint?
  get() = if (hasHitBreakpoint()) getHitBreakpoint() else null

