// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/debug/debug.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.debug.model;

@kotlin.jvm.JvmName("-initializewatchChange")
public inline fun watchChange(block: ink.debug.model.WatchChangeKt.Dsl.() -> kotlin.Unit): ink.debug.model.WatchChange =
  ink.debug.model.WatchChangeKt.Dsl._create(ink.debug.model.WatchChange.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.debug.model.WatchChange`
 */
public object WatchChangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.debug.model.WatchChange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.debug.model.WatchChange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.debug.model.WatchChange = _builder.build()

    /**
     * `string old_value = 1;`
     */
    public var oldValue: kotlin.String
      @JvmName("getOldValue")
      get() = _builder.oldValue
      @JvmName("setOldValue")
      set(value) {
        _builder.oldValue = value
      }
    /**
     * `string old_value = 1;`
     */
    public fun clearOldValue() {
      _builder.clearOldValue()
    }

    /**
     * `string new_value = 2;`
     */
    public var newValue: kotlin.String
      @JvmName("getNewValue")
      get() = _builder.newValue
      @JvmName("setNewValue")
      set(value) {
        _builder.newValue = value
      }
    /**
     * `string new_value = 2;`
     */
    public fun clearNewValue() {
      _builder.clearNewValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.debug.model.WatchChange.copy(block: `ink.debug.model`.WatchChangeKt.Dsl.() -> kotlin.Unit): ink.debug.model.WatchChange =
  `ink.debug.model`.WatchChangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

