// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v5.28.3
// source: ink/model/principal.proto

/* eslint-disable */

export const protobufPackage = "ink.model";

export interface InkPrincipal {
  id: string;
  name: string;
  roles: string[];
  isLlm: boolean;
  email: string;
}

export interface InkPrincipalInfo {
  id: string;
  displayName: string;
  email: string;
  role: string;
  isLlm: boolean;
  /** domain/user/ filesystem path */
  folderPath: string;
  /** mcp://model_name:jwt@host:port/tool */
  mcpUri: string;
}

function createBaseInkPrincipal(): InkPrincipal {
  return { id: "", name: "", roles: [], isLlm: false, email: "" };
}

export const InkPrincipal: MessageFns<InkPrincipal> = {
  fromJSON(object: any): InkPrincipal {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      roles: globalThis.Array.isArray(object?.roles) ? object.roles.map((e: any) => globalThis.String(e)) : [],
      isLlm: isSet(object.isLlm)
        ? globalThis.Boolean(object.isLlm)
        : isSet(object.is_llm)
        ? globalThis.Boolean(object.is_llm)
        : false,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: InkPrincipal): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    if (message.isLlm !== false) {
      obj.isLlm = message.isLlm;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InkPrincipal>, I>>(base?: I): InkPrincipal {
    return InkPrincipal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InkPrincipal>, I>>(object: I): InkPrincipal {
    const message = createBaseInkPrincipal();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.roles = object.roles?.map((e) => e) || [];
    message.isLlm = object.isLlm ?? false;
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseInkPrincipalInfo(): InkPrincipalInfo {
  return { id: "", displayName: "", email: "", role: "", isLlm: false, folderPath: "", mcpUri: "" };
}

export const InkPrincipalInfo: MessageFns<InkPrincipalInfo> = {
  fromJSON(object: any): InkPrincipalInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      isLlm: isSet(object.isLlm)
        ? globalThis.Boolean(object.isLlm)
        : isSet(object.is_llm)
        ? globalThis.Boolean(object.is_llm)
        : false,
      folderPath: isSet(object.folderPath)
        ? globalThis.String(object.folderPath)
        : isSet(object.folder_path)
        ? globalThis.String(object.folder_path)
        : "",
      mcpUri: isSet(object.mcpUri)
        ? globalThis.String(object.mcpUri)
        : isSet(object.mcp_uri)
        ? globalThis.String(object.mcp_uri)
        : "",
    };
  },

  toJSON(message: InkPrincipalInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.isLlm !== false) {
      obj.isLlm = message.isLlm;
    }
    if (message.folderPath !== "") {
      obj.folderPath = message.folderPath;
    }
    if (message.mcpUri !== "") {
      obj.mcpUri = message.mcpUri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InkPrincipalInfo>, I>>(base?: I): InkPrincipalInfo {
    return InkPrincipalInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InkPrincipalInfo>, I>>(object: I): InkPrincipalInfo {
    const message = createBaseInkPrincipalInfo();
    message.id = object.id ?? "";
    message.displayName = object.displayName ?? "";
    message.email = object.email ?? "";
    message.role = object.role ?? "";
    message.isLlm = object.isLlm ?? false;
    message.folderPath = object.folderPath ?? "";
    message.mcpUri = object.mcpUri ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
