// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/ical/ical.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.ical.model;

@kotlin.jvm.JvmName("-initializegeoPosition")
public inline fun geoPosition(block: ink.ical.model.GeoPositionKt.Dsl.() -> kotlin.Unit): ink.ical.model.GeoPosition =
  ink.ical.model.GeoPositionKt.Dsl._create(ink.ical.model.GeoPosition.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.ical.model.GeoPosition`
 */
public object GeoPositionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.ical.model.GeoPosition.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.ical.model.GeoPosition.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.ical.model.GeoPosition = _builder.build()

    /**
     * `double latitude = 1;`
     */
    public var latitude: kotlin.Double
      @JvmName("getLatitude")
      get() = _builder.latitude
      @JvmName("setLatitude")
      set(value) {
        _builder.latitude = value
      }
    /**
     * `double latitude = 1;`
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * `double longitude = 2;`
     */
    public var longitude: kotlin.Double
      @JvmName("getLongitude")
      get() = _builder.longitude
      @JvmName("setLongitude")
      set(value) {
        _builder.longitude = value
      }
    /**
     * `double longitude = 2;`
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.ical.model.GeoPosition.copy(block: `ink.ical.model`.GeoPositionKt.Dsl.() -> kotlin.Unit): ink.ical.model.GeoPosition =
  `ink.ical.model`.GeoPositionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

