// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/ical/ical.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.ical.model;

@kotlin.jvm.JvmName("-initializevEvent")
public inline fun vEvent(block: ink.ical.model.VEventKt.Dsl.() -> kotlin.Unit): ink.ical.model.VEvent =
  ink.ical.model.VEventKt.Dsl._create(ink.ical.model.VEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.ical.model.VEvent`
 */
public object VEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.ical.model.VEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.ical.model.VEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.ical.model.VEvent = _builder.build()

    /**
     * ```
     * Identification
     * ```
     *
     * `string uid = 1;`
     */
    public var uid: kotlin.String
      @JvmName("getUid")
      get() = _builder.uid
      @JvmName("setUid")
      set(value) {
        _builder.uid = value
      }
    /**
     * ```
     * Identification
     * ```
     *
     * `string uid = 1;`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * ```
     * SEQUENCE — modification counter
     * ```
     *
     * `int32 sequence = 2;`
     */
    public var sequence: kotlin.Int
      @JvmName("getSequence")
      get() = _builder.sequence
      @JvmName("setSequence")
      set(value) {
        _builder.sequence = value
      }
    /**
     * ```
     * SEQUENCE — modification counter
     * ```
     *
     * `int32 sequence = 2;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * ```
     * Date/Time
     * ```
     *
     * `string dt_start = 3;`
     */
    public var dtStart: kotlin.String
      @JvmName("getDtStart")
      get() = _builder.dtStart
      @JvmName("setDtStart")
      set(value) {
        _builder.dtStart = value
      }
    /**
     * ```
     * Date/Time
     * ```
     *
     * `string dt_start = 3;`
     */
    public fun clearDtStart() {
      _builder.clearDtStart()
    }

    /**
     * ```
     * Exclusive with duration
     * ```
     *
     * `string dt_end = 4;`
     */
    public var dtEnd: kotlin.String
      @JvmName("getDtEnd")
      get() = _builder.dtEnd
      @JvmName("setDtEnd")
      set(value) {
        _builder.dtEnd = value
      }
    /**
     * ```
     * Exclusive with duration
     * ```
     *
     * `string dt_end = 4;`
     */
    public fun clearDtEnd() {
      _builder.clearDtEnd()
    }

    /**
     * `.ink.ical.model.ICalDuration duration = 5;`
     */
    public var duration: ink.ical.model.ICalDuration
      @JvmName("getDuration")
      get() = _builder.duration
      @JvmName("setDuration")
      set(value) {
        _builder.duration = value
      }
    /**
     * `.ink.ical.model.ICalDuration duration = 5;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * `.ink.ical.model.ICalDuration duration = 5;`
     * @return Whether the duration field is set.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }
    public val VEventKt.Dsl.durationOrNull: ink.ical.model.ICalDuration?
      get() = _builder.durationOrNull

    /**
     * ```
     * DTSTAMP — creation timestamp
     * ```
     *
     * `string dt_stamp = 6;`
     */
    public var dtStamp: kotlin.String
      @JvmName("getDtStamp")
      get() = _builder.dtStamp
      @JvmName("setDtStamp")
      set(value) {
        _builder.dtStamp = value
      }
    /**
     * ```
     * DTSTAMP — creation timestamp
     * ```
     *
     * `string dt_stamp = 6;`
     */
    public fun clearDtStamp() {
      _builder.clearDtStamp()
    }

    /**
     * ```
     * Description
     * ```
     *
     * `string summary = 7;`
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.summary
      @JvmName("setSummary")
      set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * Description
     * ```
     *
     * `string summary = 7;`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }

    /**
     * `string description = 8;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.description
      @JvmName("setDescription")
      set(value) {
        _builder.description = value
      }
    /**
     * `string description = 8;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string location = 9;`
     */
    public var location: kotlin.String
      @JvmName("getLocation")
      get() = _builder.location
      @JvmName("setLocation")
      set(value) {
        _builder.location = value
      }
    /**
     * `string location = 9;`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }

    /**
     * `.ink.ical.model.GeoPosition geo = 10;`
     */
    public var geo: ink.ical.model.GeoPosition
      @JvmName("getGeo")
      get() = _builder.geo
      @JvmName("setGeo")
      set(value) {
        _builder.geo = value
      }
    /**
     * `.ink.ical.model.GeoPosition geo = 10;`
     */
    public fun clearGeo() {
      _builder.clearGeo()
    }
    /**
     * `.ink.ical.model.GeoPosition geo = 10;`
     * @return Whether the geo field is set.
     */
    public fun hasGeo(): kotlin.Boolean {
      return _builder.hasGeo()
    }
    public val VEventKt.Dsl.geoOrNull: ink.ical.model.GeoPosition?
      get() = _builder.geoOrNull

    /**
     * `string url = 11;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.url
      @JvmName("setUrl")
      set(value) {
        _builder.url = value
      }
    /**
     * `string url = 11;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * Status & Classification
     * ```
     *
     * `.ink.ical.model.EventStatus status = 12;`
     */
    public var status: ink.ical.model.EventStatus
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.statusValue
      @JvmName("setStatusValue")
      set(value) {
        _builder.statusValue = value
      }
    /**
     * ```
     * Status & Classification
     * ```
     *
     * `.ink.ical.model.EventStatus status = 12;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.ink.ical.model.AccessClassification classification = 13;`
     */
    public var classification: ink.ical.model.AccessClassification
      @JvmName("getClassification")
      get() = _builder.classification
      @JvmName("setClassification")
      set(value) {
        _builder.classification = value
      }
    public var classificationValue: kotlin.Int
      @JvmName("getClassificationValue")
      get() = _builder.classificationValue
      @JvmName("setClassificationValue")
      set(value) {
        _builder.classificationValue = value
      }
    /**
     * `.ink.ical.model.AccessClassification classification = 13;`
     */
    public fun clearClassification() {
      _builder.clearClassification()
    }

    /**
     * `.ink.ical.model.Transparency transp = 14;`
     */
    public var transp: ink.ical.model.Transparency
      @JvmName("getTransp")
      get() = _builder.transp
      @JvmName("setTransp")
      set(value) {
        _builder.transp = value
      }
    public var transpValue: kotlin.Int
      @JvmName("getTranspValue")
      get() = _builder.transpValue
      @JvmName("setTranspValue")
      set(value) {
        _builder.transpValue = value
      }
    /**
     * `.ink.ical.model.Transparency transp = 14;`
     */
    public fun clearTransp() {
      _builder.clearTransp()
    }

    /**
     * ```
     * 0 = undefined, 1 = highest, 9 = lowest
     * ```
     *
     * `int32 priority = 15;`
     */
    public var priority: kotlin.Int
      @JvmName("getPriority")
      get() = _builder.priority
      @JvmName("setPriority")
      set(value) {
        _builder.priority = value
      }
    /**
     * ```
     * 0 = undefined, 1 = highest, 9 = lowest
     * ```
     *
     * `int32 priority = 15;`
     */
    public fun clearPriority() {
      _builder.clearPriority()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CategoriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @return A list containing the categories.
     */
    public val categories: com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.categoriesList
      )
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @param value The categories to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.add(value: kotlin.String) {
      _builder.addCategories(value)
    }
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @param value The categories to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCategories")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @param values The categories to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllCategories(values)
    }
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @param values The categories to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCategories")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     * @param index The index to set the value at.
     * @param value The categories to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCategories")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setCategories(index, value)
    }/**
     * ```
     * Categories & Resources
     * ```
     *
     * `repeated string categories = 16;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesProxy>.clear() {
      _builder.clearCategories()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResourcesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string resources = 17;`
     * @return A list containing the resources.
     */
    public val resources: com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.resourcesList
      )
    /**
     * `repeated string resources = 17;`
     * @param value The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.add(value: kotlin.String) {
      _builder.addResources(value)
    }
    /**
     * `repeated string resources = 17;`
     * @param value The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string resources = 17;`
     * @param values The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllResources(values)
    }
    /**
     * `repeated string resources = 17;`
     * @param values The resources to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResources")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string resources = 17;`
     * @param index The index to set the value at.
     * @param value The resources to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResources")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setResources(index, value)
    }/**
     * `repeated string resources = 17;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResources")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ResourcesProxy>.clear() {
      _builder.clearResources()
    }
    /**
     * ```
     * Participants
     * ```
     *
     * `.ink.ical.model.Organizer organizer = 18;`
     */
    public var organizer: ink.ical.model.Organizer
      @JvmName("getOrganizer")
      get() = _builder.organizer
      @JvmName("setOrganizer")
      set(value) {
        _builder.organizer = value
      }
    /**
     * ```
     * Participants
     * ```
     *
     * `.ink.ical.model.Organizer organizer = 18;`
     */
    public fun clearOrganizer() {
      _builder.clearOrganizer()
    }
    /**
     * ```
     * Participants
     * ```
     *
     * `.ink.ical.model.Organizer organizer = 18;`
     * @return Whether the organizer field is set.
     */
    public fun hasOrganizer(): kotlin.Boolean {
      return _builder.hasOrganizer()
    }
    public val VEventKt.Dsl.organizerOrNull: ink.ical.model.Organizer?
      get() = _builder.organizerOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttendeesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     */
     public val attendees: com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.attendeesList
      )
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     * @param value The attendees to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAttendees")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.add(value: ink.ical.model.Attendee) {
      _builder.addAttendees(value)
    }
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     * @param value The attendees to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAttendees")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.plusAssign(value: ink.ical.model.Attendee) {
      add(value)
    }
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     * @param values The attendees to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAttendees")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.addAll(values: kotlin.collections.Iterable<ink.ical.model.Attendee>) {
      _builder.addAllAttendees(values)
    }
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     * @param values The attendees to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAttendees")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.plusAssign(values: kotlin.collections.Iterable<ink.ical.model.Attendee>) {
      addAll(values)
    }
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     * @param index The index to set the value at.
     * @param value The attendees to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAttendees")
    public operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.set(index: kotlin.Int, value: ink.ical.model.Attendee) {
      _builder.setAttendees(index, value)
    }
    /**
     * `repeated .ink.ical.model.Attendee attendees = 19;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAttendees")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Attendee, AttendeesProxy>.clear() {
      _builder.clearAttendees()
    }


    /**
     * ```
     * Recurrence (RFC 5545 §3.8.5)
     * ```
     *
     * `.ink.ical.model.RecurrenceRule rrule = 20;`
     */
    public var rrule: ink.ical.model.RecurrenceRule
      @JvmName("getRrule")
      get() = _builder.rrule
      @JvmName("setRrule")
      set(value) {
        _builder.rrule = value
      }
    /**
     * ```
     * Recurrence (RFC 5545 §3.8.5)
     * ```
     *
     * `.ink.ical.model.RecurrenceRule rrule = 20;`
     */
    public fun clearRrule() {
      _builder.clearRrule()
    }
    /**
     * ```
     * Recurrence (RFC 5545 §3.8.5)
     * ```
     *
     * `.ink.ical.model.RecurrenceRule rrule = 20;`
     * @return Whether the rrule field is set.
     */
    public fun hasRrule(): kotlin.Boolean {
      return _builder.hasRrule()
    }
    public val VEventKt.Dsl.rruleOrNull: ink.ical.model.RecurrenceRule?
      get() = _builder.rruleOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RdateProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @return A list containing the rdate.
     */
    public val rdate: com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.rdateList
      )
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @param value The rdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.add(value: kotlin.String) {
      _builder.addRdate(value)
    }
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @param value The rdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRdate")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @param values The rdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllRdate(values)
    }
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @param values The rdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRdate")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     * @param index The index to set the value at.
     * @param value The rdate to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRdate")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setRdate(index, value)
    }/**
     * ```
     * RDATE — additional recurrence dates
     * ```
     *
     * `repeated string rdate = 21;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RdateProxy>.clear() {
      _builder.clearRdate()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExdateProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @return A list containing the exdate.
     */
    public val exdate: com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.exdateList
      )
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @param value The exdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.add(value: kotlin.String) {
      _builder.addExdate(value)
    }
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @param value The exdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExdate")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @param values The exdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllExdate(values)
    }
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @param values The exdate to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExdate")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     * @param index The index to set the value at.
     * @param value The exdate to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExdate")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setExdate(index, value)
    }/**
     * ```
     * EXDATE — exception dates
     * ```
     *
     * `repeated string exdate = 22;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExdate")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ExdateProxy>.clear() {
      _builder.clearExdate()
    }
    /**
     * ```
     * RECURRENCE-ID — override instance
     * ```
     *
     * `string recurrence_id = 23;`
     */
    public var recurrenceId: kotlin.String
      @JvmName("getRecurrenceId")
      get() = _builder.recurrenceId
      @JvmName("setRecurrenceId")
      set(value) {
        _builder.recurrenceId = value
      }
    /**
     * ```
     * RECURRENCE-ID — override instance
     * ```
     *
     * `string recurrence_id = 23;`
     */
    public fun clearRecurrenceId() {
      _builder.clearRecurrenceId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AlarmsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     */
     public val alarms: com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.alarmsList
      )
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     * @param value The alarms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAlarms")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.add(value: ink.ical.model.Alarm) {
      _builder.addAlarms(value)
    }
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     * @param value The alarms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAlarms")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.plusAssign(value: ink.ical.model.Alarm) {
      add(value)
    }
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     * @param values The alarms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAlarms")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.addAll(values: kotlin.collections.Iterable<ink.ical.model.Alarm>) {
      _builder.addAllAlarms(values)
    }
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     * @param values The alarms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAlarms")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.plusAssign(values: kotlin.collections.Iterable<ink.ical.model.Alarm>) {
      addAll(values)
    }
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     * @param index The index to set the value at.
     * @param value The alarms to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAlarms")
    public operator fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.set(index: kotlin.Int, value: ink.ical.model.Alarm) {
      _builder.setAlarms(index, value)
    }
    /**
     * ```
     * Alarms
     * ```
     *
     * `repeated .ink.ical.model.Alarm alarms = 24;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAlarms")
    public fun com.google.protobuf.kotlin.DslList<ink.ical.model.Alarm, AlarmsProxy>.clear() {
      _builder.clearAlarms()
    }


    /**
     * ```
     * Timestamps
     * ```
     *
     * `string created = 25;`
     */
    public var created: kotlin.String
      @JvmName("getCreated")
      get() = _builder.created
      @JvmName("setCreated")
      set(value) {
        _builder.created = value
      }
    /**
     * ```
     * Timestamps
     * ```
     *
     * `string created = 25;`
     */
    public fun clearCreated() {
      _builder.clearCreated()
    }

    /**
     * ```
     * LAST-MODIFIED
     * ```
     *
     * `string last_modified = 26;`
     */
    public var lastModified: kotlin.String
      @JvmName("getLastModified")
      get() = _builder.lastModified
      @JvmName("setLastModified")
      set(value) {
        _builder.lastModified = value
      }
    /**
     * ```
     * LAST-MODIFIED
     * ```
     *
     * `string last_modified = 26;`
     */
    public fun clearLastModified() {
      _builder.clearLastModified()
    }

    /**
     * ```
     * Relationships
     * ```
     *
     * `string related_to = 27;`
     */
    public var relatedTo: kotlin.String
      @JvmName("getRelatedTo")
      get() = _builder.relatedTo
      @JvmName("setRelatedTo")
      set(value) {
        _builder.relatedTo = value
      }
    /**
     * ```
     * Relationships
     * ```
     *
     * `string related_to = 27;`
     */
    public fun clearRelatedTo() {
      _builder.clearRelatedTo()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttachmentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @return A list containing the attachments.
     */
    public val attachments: com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.attachmentsList
      )
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAttachments")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.add(value: kotlin.String) {
      _builder.addAttachments(value)
    }
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAttachments")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAttachments(values)
    }
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     * @param index The index to set the value at.
     * @param value The attachments to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAttachments")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAttachments(index, value)
    }/**
     * ```
     * ATTACH — URIs
     * ```
     *
     * `repeated string attachments = 28;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAttachments")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttachmentsProxy>.clear() {
      _builder.clearAttachments()
    }
    /**
     * ```
     * RFC 7986 Extensions
     * ```
     *
     * `string color = 29;`
     */
    public var color: kotlin.String
      @JvmName("getColor")
      get() = _builder.color
      @JvmName("setColor")
      set(value) {
        _builder.color = value
      }
    /**
     * ```
     * RFC 7986 Extensions
     * ```
     *
     * `string color = 29;`
     */
    public fun clearColor() {
      _builder.clearColor()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ConferencesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @return A list containing the conferences.
     */
    public val conferences: com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.conferencesList
      )
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @param value The conferences to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addConferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.add(value: kotlin.String) {
      _builder.addConferences(value)
    }
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @param value The conferences to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignConferences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @param values The conferences to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllConferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllConferences(values)
    }
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @param values The conferences to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllConferences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     * @param index The index to set the value at.
     * @param value The conferences to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setConferences")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setConferences(index, value)
    }/**
     * ```
     * CONFERENCE — video/voice URIs
     * ```
     *
     * `repeated string conferences = 30;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearConferences")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConferencesProxy>.clear() {
      _builder.clearConferences()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.ical.model.VEvent.copy(block: `ink.ical.model`.VEventKt.Dsl.() -> kotlin.Unit): ink.ical.model.VEvent =
  `ink.ical.model`.VEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ink.ical.model.VEventOrBuilder.durationOrNull: ink.ical.model.ICalDuration?
  get() = if (hasDuration()) getDuration() else null

public val ink.ical.model.VEventOrBuilder.geoOrNull: ink.ical.model.GeoPosition?
  get() = if (hasGeo()) getGeo() else null

public val ink.ical.model.VEventOrBuilder.organizerOrNull: ink.ical.model.Organizer?
  get() = if (hasOrganizer()) getOrganizer() else null

public val ink.ical.model.VEventOrBuilder.rruleOrNull: ink.ical.model.RecurrenceRule?
  get() = if (hasRrule()) getRrule() else null

