// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/event/event.proto
// Protobuf Java Version: 4.28.3

package ink.event.model;

public interface AssetLoadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.event.model.AssetLoadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.ink.asset.model.AssetRef asset = 2;</code>
   * @return Whether the asset field is set.
   */
  boolean hasAsset();
  /**
   * <code>.ink.asset.model.AssetRef asset = 2;</code>
   * @return The asset.
   */
  ink.asset.model.AssetRef getAsset();
  /**
   * <code>.ink.asset.model.AssetRef asset = 2;</code>
   */
  ink.asset.model.AssetRefOrBuilder getAssetOrBuilder();

  /**
   * <pre>
   * "IMMEDIATE", "PRELOAD", "LAZY"
   * </pre>
   *
   * <code>string priority = 3;</code>
   * @return The priority.
   */
  java.lang.String getPriority();
  /**
   * <pre>
   * "IMMEDIATE", "PRELOAD", "LAZY"
   * </pre>
   *
   * <code>string priority = 3;</code>
   * @return The bytes for priority.
   */
  com.google.protobuf.ByteString
      getPriorityBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
