# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink/model/faker.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ink/model/faker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ink/model/faker.proto\x12\tink.py.model\"]\n\x0b\x46\x61kerConfig\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x12\n\ncategories\x18\x05 \x03(\t\"r\n\rEmojiCategory\x12\r\n\x05\x65moji\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x61ker_provider\x18\x02 \x01(\t\x12\x14\n\x0cmethod_chain\x18\x03 \x01(\t\x12\x11\n\trange_min\x18\x04 \x01(\x05\x12\x11\n\trange_max\x18\x05 \x01(\x05\x42!\n\x0eink.java.modelP\x01\xaa\x02\x0cInk.Cs.Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ink.py.model.faker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016ink.java.modelP\001\252\002\014Ink.Cs.Model'
  _globals['_FAKERCONFIG']._serialized_start=36
  _globals['_FAKERCONFIG']._serialized_end=129
  _globals['_EMOJICATEGORY']._serialized_start=131
  _globals['_EMOJICATEGORY']._serialized_end=245
# @@protoc_insertion_point(module_scope)
