# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ink/model/llm.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ink/model/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ink/model/llm.proto\x12\tink.py.model\"\xda\x01\n\tGgufModel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x11hugging_face_repo\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\t\x12\x14\n\x0cquantization\x18\x05 \x01(\t\x12\x14\n\x0c\x61rchitecture\x18\x06 \x01(\t\x12\x0f\n\x07size_gb\x18\x07 \x01(\x01\x12\x13\n\x0bmin_vram_gb\x18\x08 \x01(\x05\x12\x18\n\x10jlama_compatible\x18\t \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\"\xb6\x01\n\nServiceDef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x03 \x01(\t\x12\x15\n\rdefault_model\x18\x04 \x01(\t\x12\x13\n\x0b\x61pi_key_env\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x18\n\x10requires_api_key\x18\x07 \x01(\x08\x12\x10\n\x08is_local\x18\x08 \x01(\x08\x12\x0f\n\x07\x64oc_url\x18\t \x01(\tB!\n\x0eink.java.modelP\x01\xaa\x02\x0cInk.Cs.Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ink.py.model.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016ink.java.modelP\001\252\002\014Ink.Cs.Model'
  _globals['_GGUFMODEL']._serialized_start=35
  _globals['_GGUFMODEL']._serialized_end=253
  _globals['_SERVICEDEF']._serialized_start=256
  _globals['_SERVICEDEF']._serialized_end=438
# @@protoc_insertion_point(module_scope)
