// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/structure/structure.proto
// Protobuf Java Version: 4.28.3

package ink.structure.model;

public interface StructureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.structure.model.Structure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ink.structure.model.Section sections = 1;</code>
   */
  java.util.List<ink.structure.model.Section> 
      getSectionsList();
  /**
   * <code>repeated .ink.structure.model.Section sections = 1;</code>
   */
  ink.structure.model.Section getSections(int index);
  /**
   * <code>repeated .ink.structure.model.Section sections = 1;</code>
   */
  int getSectionsCount();
  /**
   * <code>repeated .ink.structure.model.Section sections = 1;</code>
   */
  java.util.List<? extends ink.structure.model.SectionOrBuilder> 
      getSectionsOrBuilderList();
  /**
   * <code>repeated .ink.structure.model.Section sections = 1;</code>
   */
  ink.structure.model.SectionOrBuilder getSectionsOrBuilder(
      int index);

  /**
   * <code>repeated .ink.structure.model.Variable variables = 2;</code>
   */
  java.util.List<ink.structure.model.Variable> 
      getVariablesList();
  /**
   * <code>repeated .ink.structure.model.Variable variables = 2;</code>
   */
  ink.structure.model.Variable getVariables(int index);
  /**
   * <code>repeated .ink.structure.model.Variable variables = 2;</code>
   */
  int getVariablesCount();
  /**
   * <code>repeated .ink.structure.model.Variable variables = 2;</code>
   */
  java.util.List<? extends ink.structure.model.VariableOrBuilder> 
      getVariablesOrBuilderList();
  /**
   * <code>repeated .ink.structure.model.Variable variables = 2;</code>
   */
  ink.structure.model.VariableOrBuilder getVariablesOrBuilder(
      int index);

  /**
   * <code>repeated string includes = 3;</code>
   * @return A list containing the includes.
   */
  java.util.List<java.lang.String>
      getIncludesList();
  /**
   * <code>repeated string includes = 3;</code>
   * @return The count of includes.
   */
  int getIncludesCount();
  /**
   * <code>repeated string includes = 3;</code>
   * @param index The index of the element to return.
   * @return The includes at the given index.
   */
  java.lang.String getIncludes(int index);
  /**
   * <code>repeated string includes = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the includes at the given index.
   */
  com.google.protobuf.ByteString
      getIncludesBytes(int index);

  /**
   * <code>repeated .ink.structure.model.DivertRef diverts = 4;</code>
   */
  java.util.List<ink.structure.model.DivertRef> 
      getDivertsList();
  /**
   * <code>repeated .ink.structure.model.DivertRef diverts = 4;</code>
   */
  ink.structure.model.DivertRef getDiverts(int index);
  /**
   * <code>repeated .ink.structure.model.DivertRef diverts = 4;</code>
   */
  int getDivertsCount();
  /**
   * <code>repeated .ink.structure.model.DivertRef diverts = 4;</code>
   */
  java.util.List<? extends ink.structure.model.DivertRefOrBuilder> 
      getDivertsOrBuilderList();
  /**
   * <code>repeated .ink.structure.model.DivertRef diverts = 4;</code>
   */
  ink.structure.model.DivertRefOrBuilder getDivertsOrBuilder(
      int index);

  /**
   * <code>int32 total_lines = 5;</code>
   * @return The totalLines.
   */
  int getTotalLines();

  /**
   * <pre>
   * len(diverts) — convenience field
   * </pre>
   *
   * <code>int32 divert_count = 6;</code>
   * @return The divertCount.
   */
  int getDivertCount();
}
