// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/vcard/vcard.proto
// Protobuf Java Version: 4.28.3

package ink.vcard.model;

public interface VCardExtPropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.vcard.model.VCardExtProperty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "X-AUTH", "X-MCP-URI"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * e.g. "X-AUTH", "X-MCP-URI"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
