// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/ical/ical.proto
// Protobuf Java Version: 4.28.3

package ink.ical.model;

/**
 * Protobuf enum {@code ink.ical.model.AlarmAction}
 */
public enum AlarmAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ALARM_ACTION_UNSPECIFIED = 0;</code>
   */
  ALARM_ACTION_UNSPECIFIED(0),
  /**
   * <pre>
   * Display notification
   * </pre>
   *
   * <code>DISPLAY = 1;</code>
   */
  DISPLAY(1),
  /**
   * <pre>
   * Play sound
   * </pre>
   *
   * <code>AUDIO = 2;</code>
   */
  AUDIO(2),
  /**
   * <pre>
   * Send email
   * </pre>
   *
   * <code>EMAIL = 3;</code>
   */
  EMAIL(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      AlarmAction.class.getName());
  }
  /**
   * <code>ALARM_ACTION_UNSPECIFIED = 0;</code>
   */
  public static final int ALARM_ACTION_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Display notification
   * </pre>
   *
   * <code>DISPLAY = 1;</code>
   */
  public static final int DISPLAY_VALUE = 1;
  /**
   * <pre>
   * Play sound
   * </pre>
   *
   * <code>AUDIO = 2;</code>
   */
  public static final int AUDIO_VALUE = 2;
  /**
   * <pre>
   * Send email
   * </pre>
   *
   * <code>EMAIL = 3;</code>
   */
  public static final int EMAIL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AlarmAction valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AlarmAction forNumber(int value) {
    switch (value) {
      case 0: return ALARM_ACTION_UNSPECIFIED;
      case 1: return DISPLAY;
      case 2: return AUDIO;
      case 3: return EMAIL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AlarmAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AlarmAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AlarmAction>() {
          public AlarmAction findValueByNumber(int number) {
            return AlarmAction.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ink.ical.model.Ical.getDescriptor().getEnumTypes().get(6);
  }

  private static final AlarmAction[] VALUES = values();

  public static AlarmAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AlarmAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ink.ical.model.AlarmAction)
}

