// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/ical/ical.proto
// Protobuf Java Version: 4.28.3

package ink.ical.model;

/**
 * Protobuf type {@code ink.ical.model.WeekdayNum}
 */
public final class WeekdayNum extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ink.ical.model.WeekdayNum)
    WeekdayNumOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      WeekdayNum.class.getName());
  }
  // Use WeekdayNum.newBuilder() to construct.
  private WeekdayNum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WeekdayNum() {
    day_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ink.ical.model.Ical.internal_static_ink_ical_model_WeekdayNum_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ink.ical.model.Ical.internal_static_ink_ical_model_WeekdayNum_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ink.ical.model.WeekdayNum.class, ink.ical.model.WeekdayNum.Builder.class);
  }

  public static final int ORDINAL_FIELD_NUMBER = 1;
  private int ordinal_ = 0;
  /**
   * <pre>
   * -1 = last, 1 = first, etc. (0 = every)
   * </pre>
   *
   * <code>int32 ordinal = 1;</code>
   * @return The ordinal.
   */
  @java.lang.Override
  public int getOrdinal() {
    return ordinal_;
  }

  public static final int DAY_FIELD_NUMBER = 2;
  private int day_ = 0;
  /**
   * <code>.ink.ical.model.Weekday day = 2;</code>
   * @return The enum numeric value on the wire for day.
   */
  @java.lang.Override public int getDayValue() {
    return day_;
  }
  /**
   * <code>.ink.ical.model.Weekday day = 2;</code>
   * @return The day.
   */
  @java.lang.Override public ink.ical.model.Weekday getDay() {
    ink.ical.model.Weekday result = ink.ical.model.Weekday.forNumber(day_);
    return result == null ? ink.ical.model.Weekday.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ordinal_ != 0) {
      output.writeInt32(1, ordinal_);
    }
    if (day_ != ink.ical.model.Weekday.WEEKDAY_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, day_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ordinal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ordinal_);
    }
    if (day_ != ink.ical.model.Weekday.WEEKDAY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, day_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ink.ical.model.WeekdayNum)) {
      return super.equals(obj);
    }
    ink.ical.model.WeekdayNum other = (ink.ical.model.WeekdayNum) obj;

    if (getOrdinal()
        != other.getOrdinal()) return false;
    if (day_ != other.day_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDINAL_FIELD_NUMBER;
    hash = (53 * hash) + getOrdinal();
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + day_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ink.ical.model.WeekdayNum parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.ical.model.WeekdayNum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ink.ical.model.WeekdayNum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ink.ical.model.WeekdayNum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ink.ical.model.WeekdayNum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ink.ical.model.WeekdayNum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ink.ical.model.WeekdayNum prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ink.ical.model.WeekdayNum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ink.ical.model.WeekdayNum)
      ink.ical.model.WeekdayNumOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ink.ical.model.Ical.internal_static_ink_ical_model_WeekdayNum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ink.ical.model.Ical.internal_static_ink_ical_model_WeekdayNum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ink.ical.model.WeekdayNum.class, ink.ical.model.WeekdayNum.Builder.class);
    }

    // Construct using ink.ical.model.WeekdayNum.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ordinal_ = 0;
      day_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ink.ical.model.Ical.internal_static_ink_ical_model_WeekdayNum_descriptor;
    }

    @java.lang.Override
    public ink.ical.model.WeekdayNum getDefaultInstanceForType() {
      return ink.ical.model.WeekdayNum.getDefaultInstance();
    }

    @java.lang.Override
    public ink.ical.model.WeekdayNum build() {
      ink.ical.model.WeekdayNum result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ink.ical.model.WeekdayNum buildPartial() {
      ink.ical.model.WeekdayNum result = new ink.ical.model.WeekdayNum(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ink.ical.model.WeekdayNum result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ordinal_ = ordinal_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.day_ = day_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ink.ical.model.WeekdayNum) {
        return mergeFrom((ink.ical.model.WeekdayNum)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ink.ical.model.WeekdayNum other) {
      if (other == ink.ical.model.WeekdayNum.getDefaultInstance()) return this;
      if (other.getOrdinal() != 0) {
        setOrdinal(other.getOrdinal());
      }
      if (other.day_ != 0) {
        setDayValue(other.getDayValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ordinal_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              day_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int ordinal_ ;
    /**
     * <pre>
     * -1 = last, 1 = first, etc. (0 = every)
     * </pre>
     *
     * <code>int32 ordinal = 1;</code>
     * @return The ordinal.
     */
    @java.lang.Override
    public int getOrdinal() {
      return ordinal_;
    }
    /**
     * <pre>
     * -1 = last, 1 = first, etc. (0 = every)
     * </pre>
     *
     * <code>int32 ordinal = 1;</code>
     * @param value The ordinal to set.
     * @return This builder for chaining.
     */
    public Builder setOrdinal(int value) {

      ordinal_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * -1 = last, 1 = first, etc. (0 = every)
     * </pre>
     *
     * <code>int32 ordinal = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrdinal() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ordinal_ = 0;
      onChanged();
      return this;
    }

    private int day_ = 0;
    /**
     * <code>.ink.ical.model.Weekday day = 2;</code>
     * @return The enum numeric value on the wire for day.
     */
    @java.lang.Override public int getDayValue() {
      return day_;
    }
    /**
     * <code>.ink.ical.model.Weekday day = 2;</code>
     * @param value The enum numeric value on the wire for day to set.
     * @return This builder for chaining.
     */
    public Builder setDayValue(int value) {
      day_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ink.ical.model.Weekday day = 2;</code>
     * @return The day.
     */
    @java.lang.Override
    public ink.ical.model.Weekday getDay() {
      ink.ical.model.Weekday result = ink.ical.model.Weekday.forNumber(day_);
      return result == null ? ink.ical.model.Weekday.UNRECOGNIZED : result;
    }
    /**
     * <code>.ink.ical.model.Weekday day = 2;</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(ink.ical.model.Weekday value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      day_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ink.ical.model.Weekday day = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      bitField0_ = (bitField0_ & ~0x00000002);
      day_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ink.ical.model.WeekdayNum)
  }

  // @@protoc_insertion_point(class_scope:ink.ical.model.WeekdayNum)
  private static final ink.ical.model.WeekdayNum DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ink.ical.model.WeekdayNum();
  }

  public static ink.ical.model.WeekdayNum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeekdayNum>
      PARSER = new com.google.protobuf.AbstractParser<WeekdayNum>() {
    @java.lang.Override
    public WeekdayNum parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WeekdayNum> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeekdayNum> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ink.ical.model.WeekdayNum getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

