// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/table/table.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.table.model;

@kotlin.jvm.JvmName("-initializemdRow")
public inline fun mdRow(block: ink.table.model.MdRowKt.Dsl.() -> kotlin.Unit): ink.table.model.MdRow =
  ink.table.model.MdRowKt.Dsl._create(ink.table.model.MdRow.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.table.model.MdRow`
 */
public object MdRowKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.table.model.MdRow.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.table.model.MdRow.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.table.model.MdRow = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CellsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
     public val cells: com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getCellsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.cellsMap
      )
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
    @JvmName("putCells")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      .put(key: kotlin.String, value: ink.table.model.MdCell) {
         _builder.putCells(key, value)
       }
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setCells")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      .set(key: kotlin.String, value: ink.table.model.MdCell) {
         put(key, value)
       }
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeCells")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      .remove(key: kotlin.String) {
         _builder.removeCells(key)
       }
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllCells")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, ink.table.model.MdCell>) {
         _builder.putAllCells(map)
       }
    /**
     * ```
     * column_name → typed cell
     * ```
     *
     * `map<string, .ink.table.model.MdCell> cells = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearCells")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, ink.table.model.MdCell, CellsProxy>
      .clear() {
         _builder.clearCells()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.table.model.MdRow.copy(block: `ink.table.model`.MdRowKt.Dsl.() -> kotlin.Unit): ink.table.model.MdRow =
  `ink.table.model`.MdRowKt.Dsl._create(this.toBuilder()).apply { block() }._build()

