// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/debug/debug.proto
// Protobuf Java Version: 4.28.3

package ink.debug.model;

public interface WatchVariableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.debug.model.WatchVariable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string last_value = 2;</code>
   * @return The lastValue.
   */
  java.lang.String getLastValue();
  /**
   * <code>string last_value = 2;</code>
   * @return The bytes for lastValue.
   */
  com.google.protobuf.ByteString
      getLastValueBytes();

  /**
   * <code>int32 change_count = 3;</code>
   * @return The changeCount.
   */
  int getChangeCount();
}
