// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/document/document.proto
// Protobuf Java Version: 4.28.3

package ink.document.model;

public final class Document {
  private Document() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Document.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_document_model_InkFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_document_model_InkFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ink_document_model_ParseResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ink_document_model_ParseResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ink/document/document.proto\022\022ink.docum" +
      "ent.model\032\025ink/table/table.proto\"A\n\007InkF" +
      "ile\022\014\n\004name\030\001 \001(\t\022\022\n\nink_source\030\002 \001(\t\022\024\n" +
      "\014header_level\030\003 \001(\005\"c\n\013ParseResult\022*\n\005fi" +
      "les\030\001 \003(\0132\033.ink.document.model.InkFile\022(" +
      "\n\006tables\030\002 \003(\0132\030.ink.table.model.MdTable" +
      "*=\n\nEditorMode\022\033\n\027EDITOR_MODE_UNSPECIFIE" +
      "D\020\000\022\010\n\004EDIT\020\001\022\010\n\004PLAY\020\002B+\n\022ink.document." +
      "modelP\001\252\002\022Ink.Document.Modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ink.table.model.Table.getDescriptor(),
        });
    internal_static_ink_document_model_InkFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ink_document_model_InkFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_document_model_InkFile_descriptor,
        new java.lang.String[] { "Name", "InkSource", "HeaderLevel", });
    internal_static_ink_document_model_ParseResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ink_document_model_ParseResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ink_document_model_ParseResult_descriptor,
        new java.lang.String[] { "Files", "Tables", });
    descriptor.resolveAllFeaturesImmutable();
    ink.table.model.Table.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
