// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/document/document.proto
// Protobuf Java Version: 4.28.3

package ink.document.model;

public interface ParseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ink.document.model.ParseResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ink.document.model.InkFile files = 1;</code>
   */
  java.util.List<ink.document.model.InkFile> 
      getFilesList();
  /**
   * <code>repeated .ink.document.model.InkFile files = 1;</code>
   */
  ink.document.model.InkFile getFiles(int index);
  /**
   * <code>repeated .ink.document.model.InkFile files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .ink.document.model.InkFile files = 1;</code>
   */
  java.util.List<? extends ink.document.model.InkFileOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .ink.document.model.InkFile files = 1;</code>
   */
  ink.document.model.InkFileOrBuilder getFilesOrBuilder(
      int index);

  /**
   * <code>repeated .ink.table.model.MdTable tables = 2;</code>
   */
  java.util.List<ink.table.model.MdTable> 
      getTablesList();
  /**
   * <code>repeated .ink.table.model.MdTable tables = 2;</code>
   */
  ink.table.model.MdTable getTables(int index);
  /**
   * <code>repeated .ink.table.model.MdTable tables = 2;</code>
   */
  int getTablesCount();
  /**
   * <code>repeated .ink.table.model.MdTable tables = 2;</code>
   */
  java.util.List<? extends ink.table.model.MdTableOrBuilder> 
      getTablesOrBuilderList();
  /**
   * <code>repeated .ink.table.model.MdTable tables = 2;</code>
   */
  ink.table.model.MdTableOrBuilder getTablesOrBuilder(
      int index);
}
