// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/event/event.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.event.model;

@kotlin.jvm.JvmName("-initializeinkTagEvent")
public inline fun inkTagEvent(block: ink.event.model.InkTagEventKt.Dsl.() -> kotlin.Unit): ink.event.model.InkTagEvent =
  ink.event.model.InkTagEventKt.Dsl._create(ink.event.model.InkTagEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.event.model.InkTagEvent`
 */
public object InkTagEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.event.model.InkTagEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.event.model.InkTagEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.event.model.InkTagEvent = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tags = 2;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.tagsList
      )
    /**
     * `repeated string tags = 2;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * `repeated string tags = 2;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tags = 2;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * `repeated string tags = 2;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tags = 2;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * `repeated string tags = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }
    /**
     * `string knot = 3;`
     */
    public var knot: kotlin.String
      @JvmName("getKnot")
      get() = _builder.knot
      @JvmName("setKnot")
      set(value) {
        _builder.knot = value
      }
    /**
     * `string knot = 3;`
     */
    public fun clearKnot() {
      _builder.clearKnot()
    }

    /**
     * `int64 timestamp = 4;`
     */
    public var timestamp: kotlin.Long
      @JvmName("getTimestamp")
      get() = _builder.timestamp
      @JvmName("setTimestamp")
      set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 4;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResolvedAssetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     */
     public val resolvedAssets: com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.resolvedAssetsList
      )
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     * @param value The resolvedAssets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResolvedAssets")
    public fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.add(value: ink.asset.model.AssetRef) {
      _builder.addResolvedAssets(value)
    }
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     * @param value The resolvedAssets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResolvedAssets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.plusAssign(value: ink.asset.model.AssetRef) {
      add(value)
    }
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     * @param values The resolvedAssets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResolvedAssets")
    public fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.addAll(values: kotlin.collections.Iterable<ink.asset.model.AssetRef>) {
      _builder.addAllResolvedAssets(values)
    }
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     * @param values The resolvedAssets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResolvedAssets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.plusAssign(values: kotlin.collections.Iterable<ink.asset.model.AssetRef>) {
      addAll(values)
    }
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     * @param index The index to set the value at.
     * @param value The resolvedAssets to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResolvedAssets")
    public operator fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.set(index: kotlin.Int, value: ink.asset.model.AssetRef) {
      _builder.setResolvedAssets(index, value)
    }
    /**
     * ```
     * assets resolved from tags
     * ```
     *
     * `repeated .ink.asset.model.AssetRef resolved_assets = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResolvedAssets")
    public fun com.google.protobuf.kotlin.DslList<ink.asset.model.AssetRef, ResolvedAssetsProxy>.clear() {
      _builder.clearResolvedAssets()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.event.model.InkTagEvent.copy(block: `ink.event.model`.InkTagEventKt.Dsl.() -> kotlin.Unit): ink.event.model.InkTagEvent =
  `ink.event.model`.InkTagEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

