// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ink/event/event.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ink.event.model;

@kotlin.jvm.JvmName("-initializeinventoryChangeEvent")
public inline fun inventoryChangeEvent(block: ink.event.model.InventoryChangeEventKt.Dsl.() -> kotlin.Unit): ink.event.model.InventoryChangeEvent =
  ink.event.model.InventoryChangeEventKt.Dsl._create(ink.event.model.InventoryChangeEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ink.event.model.InventoryChangeEvent`
 */
public object InventoryChangeEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ink.event.model.InventoryChangeEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ink.event.model.InventoryChangeEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ink.event.model.InventoryChangeEvent = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * ```
     * equip, unequip, add, remove, use, drop
     * ```
     *
     * `string action = 2;`
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.action
      @JvmName("setAction")
      set(value) {
        _builder.action = value
      }
    /**
     * ```
     * equip, unequip, add, remove, use, drop
     * ```
     *
     * `string action = 2;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * `string emoji = 3;`
     */
    public var emoji: kotlin.String
      @JvmName("getEmoji")
      get() = _builder.emoji
      @JvmName("setEmoji")
      set(value) {
        _builder.emoji = value
      }
    /**
     * `string emoji = 3;`
     */
    public fun clearEmoji() {
      _builder.clearEmoji()
    }

    /**
     * `.ink.asset.model.AssetRef asset = 4;`
     */
    public var asset: ink.asset.model.AssetRef
      @JvmName("getAsset")
      get() = _builder.asset
      @JvmName("setAsset")
      set(value) {
        _builder.asset = value
      }
    /**
     * `.ink.asset.model.AssetRef asset = 4;`
     */
    public fun clearAsset() {
      _builder.clearAsset()
    }
    /**
     * `.ink.asset.model.AssetRef asset = 4;`
     * @return Whether the asset field is set.
     */
    public fun hasAsset(): kotlin.Boolean {
      return _builder.hasAsset()
    }
    public val InventoryChangeEventKt.Dsl.assetOrNull: ink.asset.model.AssetRef?
      get() = _builder.assetOrNull

    /**
     * `int64 timestamp = 5;`
     */
    public var timestamp: kotlin.Long
      @JvmName("getTimestamp")
      get() = _builder.timestamp
      @JvmName("setTimestamp")
      set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 5;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * ```
     * human-readable item name
     * ```
     *
     * `string item_name = 6;`
     */
    public var itemName: kotlin.String
      @JvmName("getItemName")
      get() = _builder.itemName
      @JvmName("setItemName")
      set(value) {
        _builder.itemName = value
      }
    /**
     * ```
     * human-readable item name
     * ```
     *
     * `string item_name = 6;`
     */
    public fun clearItemName() {
      _builder.clearItemName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ink.event.model.InventoryChangeEvent.copy(block: `ink.event.model`.InventoryChangeEventKt.Dsl.() -> kotlin.Unit): ink.event.model.InventoryChangeEvent =
  `ink.event.model`.InventoryChangeEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ink.event.model.InventoryChangeEventOrBuilder.assetOrNull: ink.asset.model.AssetRef?
  get() = if (hasAsset()) getAsset() else null

